### ISSUE TITLE
Don't eat up user's data bandwidth quota

### ISSUE THREAD

**Issue by sivakumar-kailasam** [ember-learn/ember-api-docs#100]
Noticed that too much bandwidth was getting utilized by the app when I was inspecting network activity by communicating a lot with cloudant. 
By the time I finishing writing down this issue the page had download about 275MB+ content from cloudant. 

<img width="967" alt="screen shot 2016-12-04 at 2 45 42 am" src="https://cloud.githubusercontent.com/assets/604117/20862248/e5f8b288-b9cb-11e6-86f6-1b10ab764127.png">

**Comment by Gaurav0** [comment]
This is what is supposed to make it browsable offline. Should we disable?

**Comment by sivakumar-kailasam** [comment]
IMHO, I'd sync one version of Ember & data docs and keep overriding it with the version the user visited recently.

**Comment by Gaurav0** [comment]
I don't think there is an efficient way to partially replicate a CouchDb database. Is there?

**Comment by Gaurav0** [comment]
Update: Yes there is! You can create a filter on the server that is nothing more than a JS function and refer to it on the client.

https://pouchdb.com/2015/04/05/filtered-replication.html

**Comment by toddjordan** [comment]
seems like we'd want our existing behavior when running offline, and do lazy loading when browsing online.  I guess one way we could differentiate this is by a url query param...

**Comment by MartinMalinda** [comment]
I don't think this feature should be enabled by default.
Maybe there could be a checkbox or two whether to download and keep in sync all versions or just latest version of API docs.
And if the syncing is in process, there could be a progress bar and also a confirmation modal on windowClose event.

**Comment by acorncom** [comment]
In the US, with bandwidth relatively cheap, having this download in the background doesn't seem too problematic.  But overseas where folks pay for data far more, I can see this being a real unpleasant surprise (especially for folks who are just starting to learn Ember) ...

**Comment by fivetanley** [comment]
Also, I think if we turn off replication, we can at least load pages we've seen before, and other stuff will stay cached.

**Comment by acorncom** [comment]
As mentioned in #132, we're aiming to shift away from CouchDB to simplify the deploy aspect of this app.  Will close this issue for now.
