### ISSUE TITLE
Should modules come before namespaces?

### ISSUE THREAD

**Issue by toddjordan** [ember-learn/ember-api-docs#102]
in the left nav of the current api docs, modules are shown before namespaces.  In the new api docs, they are shown after.  Was there a reason for this?  It may cause some confusion for those used to it they other way.  (for example there's an `ember` in both, so one might click on ember module, thinking it was a namespace.)

**Comment by toddjordan** [comment]
I'm inclined to go ahead and change the order if no objections...  cc @Gaurav0

**Comment by Gaurav0** [comment]
I don't care so go ahead. :)

**Comment by acorncom** [comment]
I think showing modules before hand is better UI 👍

**Comment by toddjordan** [comment]
So leave as is?
