### ISSUE TITLE
Modules should show parent link

### ISSUE THREAD

**Issue by toddjordan** [ember-learn/ember-api-docs#104]
Modules show a link to the parent module (usually ember)

![image](https://cloud.githubusercontent.com/assets/3609063/20868998/1c3f8932-ba37-11e6-8547-887329d1b31e.png)

**Comment by MartinMalinda** [comment]
It is fetched from `@module`
https://github.com/emberjs/website/blob/master/source/api/module.html.erb#L6

Which is provided by YUIDoc output:
https://github.com/emberjs/website/blob/master/data/api.yml#L1635

ember-jsonapi-docs do not expose this value yet:
![screen shot 2016-12-09 at 18 34 11](https://cloud.githubusercontent.com/assets/9468793/21058453/4de48f86-be3e-11e6-96df-d78ac31d3cf3.png)

Some `parentModule` relationship will probably be needed.

**Comment by toddjordan** [comment]
@esantelises is currently looking at this issue

**Comment by acorncom** [comment]
Closed by #139
