### ISSUE TITLE
Reset scroll to top when navigating routes

### ISSUE THREAD

**Issue by toddjordan** [ember-learn/ember-api-docs#105]
When you scroll down a longer item, and then switch to another item that requires scrolling the new route loads partially scrolled down-screen.  We should reset scroll to top on route change.

**Comment by MartinMalinda** [comment]
Do we want to also save scroll position for history-triggered transitions? And only reset scroll on link clicks?

If so, https://github.com/dollarshaveclub/ember-router-scroll will have to be added, which requires queryParams to be added on many places.

**Comment by toddjordan** [comment]
Honestly I'd just be happy to rest on link clicks.  We already use hashes to jump to individual methods/properties/events, so history should sort itself out somewhat with scrolling

**Comment by MartinMalinda** [comment]
Alright! Then creating a Mixin should be a sufficient solution. I'll make a PR soon.
