### ISSUE TITLE
Remove private classes from sidebar

### ISSUE THREAD

**Issue by fivetanley** [ember-learn/ember-api-docs#11]
To do this, we would need to change the documents generated by https://github.com/fivetanley/ember-jsonapi-docs.

ideally, each `project-version` document would not have a `classes` relationship anymore, but `private-classes` and `public-classes`.

I can handle this one.

**Comment by Gaurav0** [comment]
I've added this to my PR at https://github.com/ember-learn/ember-jsonapi-docs/pull/2

**Comment by toddjordan** [comment]
I think we need to de-emphasize the toggle here.  Right now its bigger/bolder than the heading.

Also, I think we need to identify private classes in the menu when shown.  italics/lighter font maybe?

![image](https://cloud.githubusercontent.com/assets/3609063/20151730/42a14f78-a689-11e6-8b9c-899935ae6e62.png)

Finally, I think what we talked about back in the day was to have an internals subdomain where users interested in internal apis could go to, but not show this to typical Ember developers.  I think we can handle this with an application config attribute. and set it on start, so when page is loaded, its already showing privates...

**Comment by Gaurav0** [comment]
I've moved Show Private to bottom to hide it better and made it smaller font size. Remaining issues are:

1) Create flag for Internals site
2) Hide checkboxes in main site

**Comment by toddjordan** [comment]
going ahead and closing this issue.  Making a new issue with remaining work.
