### ISSUE TITLE
Private classes show up under Modules when not checked in sidebar

### ISSUE THREAD

**Issue by toddjordan** [ember-learn/ember-api-docs#122]
Step 1: Make sure the "Show Private / Deprecated" Checkbox is unchecked at the bottom of the sidebar
Step 2: Open module, like ember-metal

Notice private classes, such as Descriptor are shown

**Comment by MartinMalinda** [comment]
I looked into it a little bit and it seems like we have two options:

1) Make `ember-json-api` split the `classes` attribute into `publicClasses` and `privateClasses`
2) Use the `classes` relationship instead. Load them and filter them.

**Comment by Gaurav0** [comment]
@MartinMalinda Option 1 is already done.
