### ISSUE TITLE
Fastboot fails in transitions

### ISSUE THREAD

**Issue by toddjordan** [ember-learn/ember-api-docs#128]
See fastboot issue https://github.com/ember-fastboot/ember-cli-fastboot/issues/202

Right now we are catching the error and proceeding without fastboot, but our fastboot implementation is considered broken until this issue is resolved.  It shows up for us on any transition scenario, such as going to the root url, or the url of a specific version.

**Comment by rwjblue** [comment]
A concrete solution for us here should be to rename [this afterModel](https://github.com/ember-learn/ember-api-docs/blob/c57e024894057b1fa234ff44d84e1f9ccd3478fc/app/routes/project.js#L16-L25) to `redirect` (and a few others like it).

**Comment by toddjordan** [comment]
@rwjblue thanks for looking at this. not sure it will be that simple, as afterModel in those places are doing async work.  What we can do is move the async work work being done in afterModel to the model hook, then just do the transition in afterModel or redirect (which I don't think will matter if its not async, right?)

**Comment by Gaurav0** [comment]
@rwjblue Another problem is that it seems ember tests do not wait for redirect hook before running andThen.
