### ISSUE TITLE
Add concept of Package to the left nav

### ISSUE THREAD

**Issue by toddjordan** [ember-learn/ember-api-docs#131]
The [JavaScript Modules RFC](https://github.com/emberjs/rfcs/blob/master/text/0176-javascript-module-api.md) is landing soon and our first release of the new api docs will need to support it.

The proposal is instead of splitting out the left nav into modules, namespaces, and classes, we show a tree structure the list of pacakages at the root level, expanding out into sub-packages. 

The style will be similar to XCode's doc viewer.  XCode's viewer drills down to class, function, and property, but in this case a good MVP would be just to drill down to class/namespace.

The work will involve adding the concept of a package to both our jsonapi-doc repo, and to your yuidoc.

Here's an example showing expandable packages.  Additionally, under each package we may want to show individual classes and possibly functions.  

Projects
----
**Ember**
Ember Data

Version
_Dropdown_

Packages
----
`@ember/application`
|_ deprecations
|_ globals-resolver
|_ resolver

`@ember/array`
|_mutable
|_proxy

`@ember/component`
|_ checkbox
|_ helper
|_ text-area
|_ text-field

`@ember/controller`

`@ember/debug`
|_ container-debug-adapter
|_ data-adapter

`@ember/enumerable`

`@ember/instrumentation`

`@ember/map`
|_ with-default

`@ember/object`
|_ mixin

`@ember/polyfills`

`@ember/routing`
|_ auto-location
|_ hash-location
|_ history-location
|_ link-component
|_ location
|_ none-location
|_ route
|_ router

`@ember/runloop`

`@ember/service`

`@ember/string`

`@ember/utils`

jquery

rsvp

`@ember/extensions`
|_ string
|_ array
|_ function

**Comment by toddjordan** [comment]
Pushing this out of MVP.  No data yet to work off of, and would rather focus on solidifying PWA architecture leading up to emberconf.

**Comment by sivakumar-kailasam** [comment]
This is implemented now.
