### ISSUE TITLE
Upgrade Ember

### ISSUE THREAD

**Issue by toddjordan** [ember-learn/ember-api-docs#135]
Upgrading ember to 2.11.1

**Comment by sivakumar-kailasam** [comment]
So we don't need pages from ember API docs to turn up in search engine results?

**Comment by toddjordan** [comment]
good question.  Will need to follow up with @tomdale .  I guess we can keep fastboot and deploy the app to something like heroku still but still serve data from S3

**Comment by toddjordan** [comment]
For now I'll split the issue and just upgrade ember

**Comment by acorncom** [comment]
Closed by #136
