### ISSUE TITLE
font awesome is loaded just to show one pencil icon

### ISSUE THREAD

**Issue by MartinMalinda** [ember-learn/ember-api-docs#150]
It's 7kb of css and 76kbs of fonts. I think inline SVG should be better, unless there's a plan to have more icons in the future.

**Comment by toddjordan** [comment]
Agreed, lets kill it 🔪
@MartinMalinda Do you want to pick this up and do it?

**Comment by MartinMalinda** [comment]
@toddjordan I'll kill it :)
