### ISSUE TITLE
CI tests broken due to missing credentials

### ISSUE THREAD

**Issue by sukima** [ember-learn/ember-api-docs#157]
I was surprised when PR #156 failed. Then I looked at the other PR's and all of them fail because of AWS credential problem:

```console
$ yarn run sync-docs
yarn run v0.21.3
$ s3-cli sync s3://sk-ed/json-docs public/json-docs 
This utility needs a config file formatted the same as for s3cmd
or AWS_SECRET_KEY and AWS_ACCESS_KEY environment variables.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

The command "yarn run sync-docs" exited with 1.
```

Now there is an issue that can track the fix and hopefully stem off the confusion with other PR's.

**Comment by sivakumar-kailasam** [comment]
The underlying issue is that Travis doesn't set secret variables in pull requests for security reasons. I'll be getting rid of the need to sync the docs into the repo instead load it directly off CDN. That should solve this. Thanks for reporting.

**Comment by toddjordan** [comment]
Not seeing this anymore.  Assuming fixed...
