### ISSUE TITLE
github edit link may not be correct

### ISSUE THREAD

**Issue by MartinMalinda** [ember-learn/ember-api-docs#161]
Currently the link leads to destinations like this: https://github.com/emberjs/ember.js/tree/v2.11.3/packages/ember-metal/lib/core.js#L8

Shouldn't it be
https://github.com/emberjs/ember.js/edit/master/packages/ember-metal/lib/core.js#L8 ?

**Comment by MartinMalinda** [comment]
I'm not sure how to edit docs for a certain version of Ember anyway. Since it is a tag, there is no way to do a pull request there, it can't be updated. So edits make sense only for master. Maybe we should show the edit link on latest version only?

**Comment by MartinMalinda** [comment]
Clicking the "new" edit link automatically creates a fork though. So I'm not sure if this should be done.

**Comment by toddjordan** [comment]
I think the current functionality on emberjs.com/api is to just view the source. I'm not opposed to a link to edit the file/create a pr, but it might be problematic, being on a different version of code that is doc'd.  

I guess another question is if it stays as "view", then should we use a pencil icon, or use something that represents viewing source.

**Comment by MartinMalinda** [comment]
In that case the pencil icon links to the same page as the "defined in" attribute. I think we could have an icon of Eye (as in "see the source") or code </> ("the source"). Or we could get rid of the icon completely.

**Comment by sivakumar-kailasam** [comment]
In the present iteration, it looks like this:
<img width="322" alt="screenshot 2018-01-03 10 42 55" src="https://user-images.githubusercontent.com/604117/34509676-e2c287e0-f072-11e7-9fb1-3a44f142f474.png">

Since we've added the prefix `Defined in`, I feel that it sets the expectation that you'll be viewing the source of that code. Thoughts?

**Comment by locks** [comment]
I agree with @sivakumar-kailasam.

**Comment by toddjordan** [comment]
no longer expose the pencil icon.
