### ISSUE TITLE
Warn about viewing older api docs

### ISSUE THREAD

**Issue by sivakumar-kailasam** [ember-learn/ember-api-docs#169]
For consistency with guides we should probably show the warning banner for older docs,

<img width="891" alt="screenshot 2017-03-20 17 13 30" src="https://cloud.githubusercontent.com/assets/604117/24098519/bcde8d50-0d90-11e7-9328-ee1635602a3a.png">

**Comment by acorncom** [comment]
Hmm, not sure if I agree.  My goal was to eliminate everything but the current guides from Google search results (using a `robots.txt file or equiv) but I think if I were working on a project I would deliberately make sure I was on the right version of the api docs (far more than with guides).  In which case it might be annoying to have that reminder all the time ... :grinning:

**Comment by sivakumar-kailasam** [comment]
Sounds reasonable, but I've seen cases where someone links an older version of docs in their posts and user ends up landing there. May be on both guides as well as in docs we should have a `/latest` version route. Or even `lts`(takes to latest LTS) that could solve that problem.

**Comment by acorncom** [comment]
We've got a `/current` that can be used for guides (and that I'd like to get setup here long-term).  And yes, an `lts` (possibly without the banner?) is something someone else mentioned too

**Comment by sivakumar-kailasam** [comment]
Since we're adding LTS & current/release support in url slugs, this wouldn't be an issue anymore
