### ISSUE TITLE
Search results page

### ISSUE THREAD

**Issue by mschinis** [ember-learn/ember-api-docs#176]
# What
Since we use Algolia to power our autocomplete, we can also use algolia to power our own search results page. This could show up when the user hits the "Enter" key, and each result could show more information about every search result.

# Why
There's a couple of really positive things here.
1. Opensearch 
This makes it easy to search a website without even opening the site. This is very handy for developers when they know what they're looking for, and just want to get to there as soon as possible. I made a quick PR on EmberObserver (https://github.com/emberobserver/client/pull/45) that you can get more information if you want to.

2. More context
The autocomplete dropdown is great, but doesn't give you enough information to help you make a decision whether the result you are about to click is what you're actually looking for.

3. Filters
This is possibly the least important reason right now, but creating a dedicated search results page also gives us the room to start adding filters, like;
   - Module
   - Module version

# When
This could be left post-EmberConf given the time constraints we have, but I can start working on it as soon as #143 is done and merged in.

**Comment by toddjordan** [comment]
Moved to Feature backlog project https://github.com/ember-learn/ember-api-docs/projects/5
