### ISSUE TITLE
Visiting older version of docs while on a newly introduced class causes errors that aren't handled

### ISSUE THREAD

**Issue by sivakumar-kailasam** [ember-learn/ember-api-docs#179]
Visit `ember/2.12.0/classes/Ember.Engine` and switch version on the left to any 1.x version. The app immediately try to makes a request for a class that doesn't exist so the app is left in a broken state.

**Comment by toddjordan** [comment]
optimally we'd do a transition with a message instead of showing blank content.

**Comment by toddjordan** [comment]
At the learn team meeting today @locks preference was to support loading the older patch level urls, but always show content for the latest patch at that minor version.  

@locks is this correct? or do we want to redirect the older patch url to the latest patch.

**Comment by locks** [comment]
As discussed in Slack, we'll use major.minor everywhere.

**Comment by mschinis** [comment]
@locks 
does the above mean we should change the URL structure to only be `major.minor`?

I think we should keep the `major.minor.patch` on the URL, and just use `major.minor` internally.

**Comment by locks** [comment]
> does the above mean we should change the URL structure to only be major.minor?

Yup

**Comment by toddjordan** [comment]
@mschinis I think the preference is to use major.minor in the url, and redirect major.minor.patch to major.minor.

**Comment by toddjordan** [comment]
looks like @sivakumar-kailasam is taking a stab at this in #261

**Comment by mschinis** [comment]
agh, i had already started working on this 😩 
I'll pick up one of the other tasks i was assigned to
