### ISSUE TITLE
Both app cache and service worker are running simultaneously in chrome

### ISSUE THREAD

**Issue by toddjordan** [ember-learn/ember-api-docs#182]
When you go to the web page in Chrome and look at the console, you see the list of appcache files being downloaded.  You also see the service worker registered.

They are doing duplicate tasks and the goal is to only run appcache on non-service worker environments.  

Supposedly appcache won't run if there are service workers in effect.  Problem is how to start the service workers (which are part of ember-service-workers) before appcache initializes.

**Comment by sivakumar-kailasam** [comment]
If we can't find much info out there we can ask chrome devs on chromiumdev.slack.com.

**Comment by sivakumar-kailasam** [comment]
I've brought back only service workers with #210. Wondering if with the server side caching schemes & being on fastly if we need to provide offline experience for IE & safari since app cache seems tricky to handle

**Comment by toddjordan** [comment]
For now, we've removed service workers/app cache from the project due to problems created by our website proxy scheme.  Will revisit at a later date once some higher priority stuff lands.  For now fastly cdn is making things pretty snappy.
