### ISSUE TITLE
Add Google Analytics tracking to the site

### ISSUE THREAD

**Issue by acorncom** [ember-learn/ember-api-docs#183]
I'd like to get our Google Analytics tracking code added to the new app (`UA-27675533-1`) so that we can track page views within the app over time.  We'd preferably also disable tracking when we're doing development and only track this in production ...

**Comment by sivakumar-kailasam** [comment]
@MartinMalinda https://developers.google.com/web/updates/2016/07/offline-google-analytics in case this interests you after I land the service worker changes

**Comment by MartinMalinda** [comment]
@sivakumar-kailasam interesting. We can create an issue for this once we have service workers set up.
