### ISSUE TITLE
Redirect old urls to the corresponding page in the new viewer

### ISSUE THREAD

**Issue by acorncom** [ember-learn/ember-api-docs#184]
PRs for this issue can be explored simultaneously with #185 and https://github.com/ember-learn/ember-api-docs/issues/216, but the solution for this is blocked until we have clarity on both:

- [ ] need a `/current` url to redirect all old urls to #185
- [ ] do anchor tags survive a redirect sent by our backend? https://github.com/ember-learn/ember-api-docs/issues/216

Before we shift out of `beta` and replace the main api docs pages on the Ember website, we need to ensure that we've properly remapped all old api urls to their corresponding pages in the new Ember app.  Some of our `namespaces` (as shown on the old sidebar) actually have the word `classes` in their url, and we'll need to account for that

Example urls that we'll want to redirect:

- http://emberjs.com/api/modules/ember-application.html (module) -> `/api/ember/current/modules/ember-application`
- http://emberjs.com/api/classes/Ember.computed.html (namespace) -> `/api/ember/current/namespaces/Ember.computed`
- http://emberjs.com/api/classes/Ember.Application.html (class) -> `/api/ember/current/namespaces/Ember.computed`

To do:
- [ ] add mappings for the items above (we'll want to map roughly as above) to https://github.com/emberjs/website/blob/master/static.json using the needed syntax for the Heroku buildpack we're using: https://github.com/heroku/heroku-buildpack-static#custom-redirects  We'll want to do 301 redirects to end up replacing our pages in search engine indices as well ...
- [x] adjust our main website proxy url to be at `/api` instead of `api-new` (https://github.com/emberjs/website/blob/master/static.json#L4)
- [ ] send in a PR to `emberjs/website` for the above changes with a "DON'T MERGE" title (as we want to make sure this happens when desired and not because someone merges before we're ready)

**Comment by sivakumar-kailasam** [comment]
the rewrite engine should probably be fed a map based on 2.12's docs since some urls will have to land at ember and others at ember-data.

**Comment by toddjordan** [comment]
We possibly also need a strategy for redirecting `#` method, property, and event links to the current strategy of url params.  Either that or support hash based navigation in the new app as well.

**Comment by acorncom** [comment]
@sivakumar-kailasam Confirmed on the mapping.  My impression as I look at our url structure though is that we may not need a complete mapping, but may be able to handle a simpler set of wildcard rules that handle things.

**Comment by acorncom** [comment]
Also opened a new issue for us to track info on @toddjordan's comment above

**Comment by toddjordan** [comment]
Supporting legacy module URLs: https://github.com/ember-learn/ember-api-docs/pull/242

**Comment by toddjordan** [comment]
Also #249 and #253 

Should be good to go

**Comment by toddjordan** [comment]
not quite how written up, but /api is live now 🙃
