### ISSUE TITLE
Add a /current route that we can use in various places

### ISSUE THREAD

**Issue by acorncom** [ember-learn/ember-api-docs#185]
At times we need the ability to link to "the most current" version of api docs (see https://github.com/ember-learn/ember-api-docs/issues/184 for an example). We need to add a `/current` route to this Ember app that will display the most current version of the api docs.

**Comment by MartinMalinda** [comment]
I could implement it by sorting projectVersions relationships with something like https://github.com/ragingwind/semver-sort. But maybe it would be better to sort it already in jsonapi-docs project. It would probably be more efficient.

**Comment by sivakumar-kailasam** [comment]
we already have an array of sorted versions based on semver. We just need to handle `/ember/current/` in the route load the latest one 😄

**Comment by MartinMalinda** [comment]
I does not seem to be sorted here: https://ead-sk.global.ssl.fastly.net/rev-index/ember.json. Maybe I am looking at wrong place?

**Comment by sivakumar-kailasam** [comment]
Oh its done part of the app in that route's [controller](https://github.com/ember-learn/ember-api-docs/blob/d18a0b2454150457d67e1119b9ca95e3dac460c4/app/controllers/project-version.js#L68)

**Comment by MartinMalinda** [comment]
I see, that's great then. I will use that. Probably will have to move it to the model though.

**Comment by toddjordan** [comment]
Would be cool instead of or in addition to `/current`, to have `/release`, `/lts`, and maybe eventually `/beta` and `/canary`

**Comment by toddjordan** [comment]
correct, though I feel like "release" would be clearer to what "current" means.  Current could mean canary or beta or lts as well.

**Comment by MartinMalinda** [comment]
Maybe we should reopen this? I will revisit this once the route structure refactor is merged.
