### ISSUE TITLE
Create a web app manifest

### ISSUE THREAD

**Issue by toddjordan** [ember-learn/ember-api-docs#188]
Part of making the app a PWA, we need to make a good web-app manifest: https://developer.mozilla.org/en-US/docs/Web/Manifest

**Comment by oskarrough** [comment]
https://github.com/san650/ember-web-app

**Comment by sivakumar-kailasam** [comment]
The theme color and logo images to be used can be seen in the styles.

**Comment by sivakumar-kailasam** [comment]
Addressed by #210
