### ISSUE TITLE
Links to subroutes are sometimes broken on first load

### ISSUE THREAD

**Issue by MartinMalinda** [ember-learn/ember-api-docs#213]
Links to subroutes like methods, events are sometimes broken.
```
This link-to is in an inactive loading state because at least one of its parameters presently has a null/undefined value, or the provided route name is invalid.
```

I think it would be better to rather not change the tagName of link-to as it is done here:
https://github.com/ember-learn/ember-api-docs/blob/100b9174047ece8290800a60b41fc1a7f86d9e15/app/templates/project-version/class.hbs#L51

Or maybe even switch to ember-href-to to increase performance.

**Comment by toddjordan** [comment]
Hey @MartinMalinda can you try this out and let us know if its still an issue, and if it affects usage?

**Comment by MartinMalinda** [comment]
@toddjordan Yes, it still happens with FastBoot roughly on 1 in 15 loads. I think it was more common before but I may be mistaken.
