### ISSUE TITLE
Service workers, web app manifest, and appcache don't work in deployment

### ISSUE THREAD

**Issue by toddjordan** [ember-learn/ember-api-docs#214]
This is because we have a complicated proxy system to get us hosting at emberjs.com/api-new

* emberjs.com goes to our heroku website deployment.
* the website has a static.json that proxies to our fastly site (https://ember-api-docs-staging-herokuapp-com.global.ssl.fastly.net/): https://github.com/emberjs/website/blob/master/static.json
* our app redirects url visits to the root to `api-beta`.
* if we specify our sw root to `/api-beta/sw.js`, then fastboot server returns to us a 500 error.

Therefore we can't load sw.js currently.

Having this proxy/redirect scheme makes service workers (as well as using appcache and web manifest) difficult if not currently impossible.

One possibility is to just host the api viewer at api.emberjs.com (similar to how guides currently are).  This would allow the files to load from root like they seem to be meant to be.

**Comment by acorncom** [comment]
Per discussions at the learning team meeting today, we're going to hold off on work on this until after our v1 milestone.  To unblock this, we'll either need to manually copy over the generated service worker file to the root of https://www.emberjs.com (via the emberjs/website repo) or wait until we've shifted the main site to Fastboot/Engines as well.

**Comment by mattmarcum** [comment]
Just curious, what's the 500 error returned by the fastboot server?

**Comment by acorncom** [comment]
@mattmarcum Still curious on the 500 error? We've got a working staging environment these days, so could probably get going on this again if you have the time/interest to help push on it ...

**Comment by toddjordan** [comment]
Closing for now since we aren't currently supporting offline.  We may pick this up again soon.
