### ISSUE TITLE
Make sure we properly shift to anchor tags within our pages for old urls

### ISSUE THREAD

**Issue by acorncom** [ember-learn/ember-api-docs#216]
As mentioned by @toddjordan here (https://github.com/ember-learn/ember-api-docs/issues/184#issuecomment-291191836), we want to continue to support old anchor tags:

> We possibly also need a strategy for redirecting # method, property, and event links to the current strategy of url params. Either that or support hash based navigation in the new app as well.

Currently, urls like the following are put out and used liberally on StackOverflow, internal documentation and all sorts of other places we have no control over:

- https://emberjs.com/api/#method_isArray
- https://emberjs.com/api/classes/Ember.Route.html#method_activate

We need to ensure that those urls continue to play nicely with our new setup.  This issue may block implementation of https://github.com/ember-learn/ember-api-docs/issues/184 if we find that doing a redirect to our newly supported urls (using our emberjs/website repo) eliminate the anchor tags that our Ember app will need ...

**Comment by sivakumar-kailasam** [comment]
We could probably rewrite this in a before middleware on FastBoot to redirect to the correct url with these values as query params

**Comment by toddjordan** [comment]
Addressed by #249 #253 #242
https://emberjs.com/api-beta/#method_isArray
https://emberjs.com/api-beta/classes/Ember.Route.html#method_activate
