### ISSUE TITLE
Refactor api-docs route structure

### ISSUE THREAD

**Issue by mschinis** [ember-learn/ember-api-docs#220]
### The problem

Our current solution for indexing the api-docs in Algolia relies on Algolia's docsearch. We have [this JSON](https://github.com/algolia/docsearch-configs/blob/master/configs/emberjs_versions.json) that describes how the docsearch scraper reads the website and follows the various links to construct a full index of all the api docs.

In order to write an equivalent json configuration, we need to use classes that the scraper will identify as level1/level2/etc of the hierarchy. An example hierarchy would be the following:
`API (lvl0) > Modules (lvl1) > ember (lvl2) > Ember.ContainerDebugAdapter (lvl3)`
for this url `https://www.emberjs.com/api-beta/ember/2.12.0/modules/ember-debug`

Right now, we have a `current` class on each element in the hierarchy, that helps us:
1. Style and give better visual feedback to the person reading the docs
2. Extract the full hierarchy using the docsearch scraper

*Example of what it looks like on current docs*

![](http://take.ms/e7pam)

Similarly to the above, navigating to this url `https://www.emberjs.com/api-beta/ember/2.12.0/modules/ember-debug` should have applied a class that the scraper can identify as being lvl1. Investigating this further, this is because the lvl1 links are essentially plain `<a>` tags with no logic to apply an identifiable class.

*Example of beta api-docs*
![](http://take.ms/skbyj)

### The solution

The proposed solution here would be to use ember's `{{link-to}}` and delegate all of that logic to it.
Since ember does the url detection very well, and handles any class updates depending on the url on its own, I think it's very appropriate to use hand all of this to ember.

Given the url structure in the `router.js` looks like the following
```javascript
    this.route('namespace', {path: '/namespaces/:module'}, itemRoutes);
```

A link-to lvl1 anchor that automatically updates the current class is not possible.

I propose we restructure the routes, to something like the following:

```javascript
this.route('namespaces', function () {
    this.route('namespace', { path: '/:module' });
});
```

Making the above restructure would allow us to use the `link-to` to create something like the following:
```hbs
{{#link-to 'namespaces' }}
  Modules
{{/link-to}}
```

Ofcourse, this will require us to also update any existing links to the `namespace` route to point to `namespaces.namespace`.

Similarly to the above example of `/namespace/:module`, we will need to do the same for;
1. `/modules/:module`
2. `/classes/:class`

This is a big blocker on getting the correct Algolia hierarchy, and eventually getting the new api docs to production, so any feedback or alternative recommendations are very welcome before I actually start working on this this week

**Comment by toddjordan** [comment]
I am for clearing out this blocker 👍 
I think it will also allow us to have a default behavior for navigating to just /namespaces (which I think just errors today)
There are some incoming updates to default navigation that you might have to consider (though not sure how much it will affect): https://github.com/ember-learn/ember-api-docs/pull/219

But overall, I think we should move forward with it.

**Comment by mschinis** [comment]
perfect, thanks @toddjordan, I'll get cracking on this today and tomorrow
