### ISSUE TITLE
strange redirects from https to http

### ISSUE THREAD

**Issue by MartinMalinda** [ember-learn/ember-api-docs#231]
visiting https://www.emberjs.com/api-beta results in

301 https://www.emberjs.com/api-beta
301 **http**://www.emberjs.com/api-beta (switch to http)
307 **https**://www.emberjs.com/api-beta/ (back to https)
301 http://www.emberjs.com/api-beta/ember/2.12.0/namespaces/Ember
and finally 200  https://www.emberjs.com/api-beta/ember/2.12.0/namespaces/Ember (https again)
(4 redirects)

Link to api-beta without the trailing slash will probably not be common but there is redundant redirect in `/api-beta/` as well:

307 https://www.emberjs.com/api-beta/
301 http://www.emberjs.com/api-beta/ember/2.12.0/namespaces/Ember
200 https://www.emberjs.com/api-beta/ember/2.12.0/namespaces/Ember
(2 redirects)

These redirects are also probably causing extra burden on the server.

And then, even if this is fixed and there is just one redirect I think we should be using `http://www.emberjs.com/api-beta/ember/latest/namespaces/Ember` link wherever possible to avoid that redirect as well, since firing up Fastboot twice is costly.

We could also hardcode `/api-docs/` redirect somewhere higher up so it does not need to be done by FastBoot and so it is faster.

**Comment by MartinMalinda** [comment]
Maybe few of the redirects could be hard coded right here: https://github.com/emberjs/website/blob/master/static.json#L22

**Comment by sivakumar-kailasam** [comment]
With the latest deployment the second secenario is no longer applicable/works as expected,
<img width="350" alt="screenshot 2017-06-15 01 04 18" src="https://user-images.githubusercontent.com/604117/27150918-934a310a-5166-11e7-9cce-d441da1379b9.png">

the first scenario still seems to exist. I've reached out to @hone via slack.
<img width="962" alt="screenshot 2017-06-15 01 08 25" src="https://user-images.githubusercontent.com/604117/27151197-74ed949e-5167-11e7-923d-e65155fb35ab.png">

**Comment by toddjordan** [comment]
no longer api-beta
