### ISSUE TITLE
<title> is always the same in FastBoot

### ISSUE THREAD

**Issue by MartinMalinda** [ember-learn/ember-api-docs#244]
It seems like in FastBoot the `<title>` is always "Ember API Documentation" and the correct title is set on client side only

**Comment by MartinMalinda** [comment]
Seems like this: https://github.com/ember-learn/ember-api-docs/blob/master/app/routes/application.js#L8 is not executed in FastBoot. The CDN prefetch remains empty as well.

**Comment by sivakumar-kailasam** [comment]
I think I know why it might be happening. Will take a look

**Comment by MartinMalinda** [comment]
My bad, this is set correctly - `<meta property="og:title" content="ember-runtime - 2.13.3 - Ember API Documentation">`

Maybe we could remove `"ember-cli-document-title` and change title via `ember-cli-head` ?
