### ISSUE TITLE
Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by MartinMalinda** [ember-learn/ember-api-docs#245]
This error occurs for me when searching the input box.

It seems to be breaking on this line: https://github.com/ember-learn/ember-api-docs/blob/72f70135f25a00bed8863f5d913ff42549d359f1/app/components/search-input/dropdown.js#L33

**Comment by mschinis** [comment]
@MartinMalinda @sivakumar-kailasam 

Missed this at the time. I noticed this happening on the weekend as I was working on the algolia branch and I fixed it here. https://github.com/ember-learn/ember-api-docs/pull/290

**Comment by toddjordan** [comment]
fixed
