### ISSUE TITLE
Improve performance

### ISSUE THREAD

**Issue by MartinMalinda** [ember-learn/ember-api-docs#246]
I did a little bit of performance checkup and profiling today. I believe some things could significantly improve performance.

- `link-to`'s are very expensive and there's a lot of them. Moving to `ember-href-to` would have a very positive impact on perf. Href-to has some issues with dynamic changes of query-params but I think it's worth a try.
- `href-to` could be then memoized for further perf increase
- background reloading in Ember data could be turned off, since data are mostly static anyway
- `tether.js` is a bit expensive
- install https://github.com/salsify/ember-cli-dependency-lint
 - remove lodash?

**Comment by toddjordan** [comment]
performance seems to be pretty good atm.  Maybe do some payload analysis and profiling in the future but for now we will continue as is.  Thanks for looking at it.
