### ISSUE TITLE
Use the new glimmer navbar(page header) & common footer

### ISSUE THREAD

**Issue by sivakumar-kailasam** [ember-learn/ember-api-docs#255]
Refer to https://github.com/emberjs/website/pull/2930/files & https://github.com/ember-learn/glimmer-styleguide

**Comment by MartinMalinda** [comment]
I'm afraid this could negatively affect performance and it might be problematic to render it on the server.
Ideally, we could import just the template from https://github.com/ember-learn/glimmer-styleguide/blob/master/src/ui/components/main-navbar/template.hbs. I'm not sure if that can be done though.

**Comment by sivakumar-kailasam** [comment]
@MartinMalinda may be @locks or someone from #glimmer channel can answer this concern.

**Comment by locks** [comment]
I don't think we should do it until we have SSR.
Relatedly, where's the footer?

**Comment by toddjordan** [comment]
for version 1, lets migrate styles/markup until the "ember+glimmer=❤️" situation is better.

**Comment by toddjordan** [comment]
Created #257 for that
