### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by locks** [ember-learn/ember-api-docs#258]
This app should have a footer, like Guides and emberjs.com.

Port the [main-footer component](https://github.com/ember-learn/glimmer-styleguide/tree/master/src/ui/components/main-footer) from glimmer-styleguide, and the [respective CSS](https://github.com/ember-learn/glimmer-styleguide/blob/master/src/ui/styles/main-footer.scss).

**Comment by sivakumar-kailasam** [comment]
closed via #264
