### ISSUE TITLE
Use StaticBoot instead of FastBoot

### ISSUE THREAD

**Issue by MartinMalinda** [ember-learn/ember-api-docs#260]
This is quite a crazy idea but since API Docs are just static content, we could use StaticBoot to build static HTML files and deploy those to the server. This would significantly improve initial loading time. 

I've done this before on small sites via some shell scripts (https://medium.com/developers-writing/generating-static-websites-with-ember-cli-and-fastboot-88f0d2db13cb)

But nowadays there's even an add-on for it:
https://github.com/robwebdev/ember-cli-staticboot

The cons here would probably be extra overhead and potentially much longer deployment times. There would be a lot of content to pre-generate.

An easier alternative would be some kind of caching strategy on the FastBoot side but I am not sure FastBoot has it yet.

**Comment by sivakumar-kailasam** [comment]
@MartinMalinda if we play around with some fastly configuration changes, we should be able to cache the fastboot rendered pages on fastly and purge when we generate new docs for patch releases.  This should significantly reduce the load on the server & make the subsequent page loads crazy fast.

**Comment by locks** [comment]
https://github.com/Motokaptia/ember-cli-prerender

**Comment by MartinMalinda** [comment]
@sivakumar-kailasam if the purge can be hooked into Travis, that sounds like the most viable solution for our use-case 👍

**Comment by sivakumar-kailasam** [comment]
Heroku's post deploy script can take care of it I guess :)

**Comment by acorncom** [comment]
We initially decided to deliberately use Fastboot to both provide SEO support and also provide a reference implementation of a Fastboot app that the entire community could interact with. 

From an SEO perspective, we may not need Fastboot and our search provider also supports SPAs. But that doesn't remove the desire to have a good Fastboot implementation that we can point people to. I'd suggest that we use staticboot / prerender options for the website and guides, but leave API docs as-is

**Comment by sivakumar-kailasam** [comment]
Not to mention the gazillion pages that will get generated for all those versions 😅.

**Comment by sivakumar-kailasam** [comment]
We've been content with FastBoot for the past year that we've been in production. We can revisit this if the need ever comes up.
