### ISSUE TITLE
Items missed in v1

### ISSUE THREAD

**Issue by sivakumar-kailasam** [ember-learn/ember-api-docs#266]
Search input was commented out in #264. This has caused other elements to move around a bit since they're center aligned. Need to enable it again & match header with the rest of the site.

- [ ] Scroll behavior was broken with styling changes
- [ ] Header & footer aren't mobile friendly similar to the rest of the website.
- [ ] Bring back search & make it work
- [ ] Match header with main site
- [ ] Fix manifest.json generation

**Comment by alexander-alvarez** [comment]
The feature I'm most missing is the link icon on hover of method / properties to get an anchor link.
a la:
![image](https://user-images.githubusercontent.com/11779993/28075151-95684cd4-6628-11e7-8fb5-d2b73c0b91c3.png)

I can help out with this sometime soon if need be

**Comment by toddjordan** [comment]
converted each of these to separate issues
#271, #272, #273, #274, #275
