### ISSUE TITLE
API documentation for Ember.DS has been removed

### ISSUE THREAD

**Issue by abrinckm** [ember-learn/ember-api-docs#270]
Pages I had previously referenced are gone from your API docs!!

I'm looking for documentation specifically for `DS.RESTAdapter` hook functions, as well as `store` functions (such as save, create, delete, etc.), however they have mysteriously disappeared from the documentation. 

The guides and tutorials are insufficient and do not provide the depth of information I need. Those API docs were very helpful to me :)

If these classes have been deprecated for latest version of Ember, then I believe they should still appear in docs for previous versions where they still exist.

**Comment by abrinckm** [comment]
For those reading, I found alternative documentation at [ember-doc](http://www.ember-doc.com/). I can start using that site to get the information I need. 
However, I still believe those docs should exist here: https://emberjs.com/api/ so I'm keeping this issue open for someone else to close.

**Comment by sivakumar-kailasam** [comment]
@abrinckm There was a minor css glitch because of which the project selector on the sidebar wasn't visible which is now fixed. If you select ember-data you should still see everything you're looking for. https://emberjs.com/api/ember-data/2.14/classes/DS.RESTAdapter

**Comment by abrinckm** [comment]
Nice! thank you :)
