### ISSUE TITLE
Get urls to specific methods/props/events by clicking anchor image on heading

### ISSUE THREAD

**Issue by toddjordan** [ember-learn/ember-api-docs#271]
(missing feature from legacy ruby app)

**Comment by toddjordan** [comment]
Links to individual items follow the format ex:
https://emberjs.com/api/ember/2.14/classes/Ember.Route/methods/activate?anchor=activate

Blocked by issue #273

**Comment by toddjordan** [comment]
cc @alexander-alvarez

**Comment by mikoscz** [comment]
I'm taking this one ;)

**Comment by alexander-alvarez** [comment]
:beers:

**Comment by alexander-alvarez** [comment]
@mikoscz have you started on this? I can tackle today or tomorrow if not
