### ISSUE TITLE
scroll behavior broken :-(

### ISSUE THREAD

**Issue by toddjordan** [ember-learn/ember-api-docs#273]

**Comment by sivakumar-kailasam** [comment]
Enable the test suite at https://github.com/ember-learn/ember-api-docs/blob/master/tests/acceptance/scroll-reset-on-transition-test.js to start solving issues on this.

**Comment by MartinMalinda** [comment]
I know what's the issue. Will send PR soon.

**Comment by sivakumar-kailasam** [comment]
@MartinMalinda it broken when i changed the styles if that helps :/
