### ISSUE TITLE
Header/Footer Styling on Mobile

### ISSUE THREAD

**Issue by toddjordan** [ember-learn/ember-api-docs#274]

**Comment by toddjordan** [comment]
cc @Turbo87

**Comment by toddjordan** [comment]
partially addressed by https://github.com/ember-learn/ember-api-docs/pull/269

**Comment by jenweber** [comment]
PR https://github.com/ember-learn/ember-api-docs/pull/320

**Comment by toddjordan** [comment]
@jenweber do you think this is closable?

**Comment by jenweber** [comment]
Yes. Closed.
