### ISSUE TITLE
Rename Modules to Packages

### ISSUE THREAD

**Issue by locks** [ember-learn/ember-api-docs#285]
We currently have a header in the table of contents that reads "Modules", as well as a route segment "/modules". This should be renamed to "Packages"  and "/packages".

I'm wondering if we can just rename it as it's very early days, or we have to include aliases?

**Comment by amyrlam** [comment]
👋 explored the repo some for the first time today! i can take a stab at this one

**Comment by sivakumar-kailasam** [comment]
As long as `/modules` can redirect to `/packages` so that we don't break bookmarked/indexed urls out there.
