### ISSUE TITLE
Copying code block is including the line no

### ISSUE THREAD

**Issue by kumkanillam** [ember-learn/ember-api-docs#286]
Copying the code block comes with line no, but in [ember guides](https://guides.emberjs.com) it's copying without line no. It would be great if we can copy the code without line no.

**Comment by sivakumar-kailasam** [comment]
For reference,

in https://guides.emberjs.com/v2.14.0/components/defining-a-component/
![guides_copy_code](https://user-images.githubusercontent.com/604117/28217363-82246fe8-68d2-11e7-9637-2997a1eebd88.gif)

in https://emberjs.com/api/ember-data/2.14/classes/DS.Adapter
![api_copy_code](https://user-images.githubusercontent.com/604117/28217352-7aa7d912-68d2-11e7-82a5-219b0fa0d2d4.gif)

**Comment by jenweber** [comment]
PR'd. I wasn't able to figure out why it behaves differently in the Docs vs Guides, but I think the change is better overall.

**Comment by sivakumar-kailasam** [comment]
@jenweber interestingly guides doesn't have css for `user-select:none` on these elements ¯\_(ツ)_/¯ .
