### ISSUE TITLE
Main container chapter has variable width

### ISSUE THREAD

**Issue by makepanic** [ember-learn/ember-api-docs#287]
When comparing https://emberjs.com/api/ember/2.14/namespaces/Ember with https://emberjs.com/api/ember/2.14/classes/Ember.Controller one can see that the chapter content width is different.
This is most likely caused by `main.container .content .chapter` only using `max-width` (800px) instead of using a fixed width.

**Comment by mikoscz** [comment]
@sivakumar-kailasam I think that we can close this one 😄
