### ISSUE TITLE
Visually differentiate type and definition.

### ISSUE THREAD

**Issue by Serabe** [ember-learn/ember-api-docs#294]
In method documentation the type of a param / return value is not visually different than the documentation of it:

![2017-07-19 at 20 37](https://user-images.githubusercontent.com/36221/28383819-bc088f02-6cc2-11e7-81a1-7ff1b84d9642.png)

![2017-07-19 at 20 37](https://user-images.githubusercontent.com/36221/28383834-c4aa578a-6cc2-11e7-8b8b-222b540f3723.png)

**Comment by sivakumar-kailasam** [comment]
//cc @Turbo87

**Comment by Turbo87** [comment]
<img width="1135" alt="bildschirmfoto 2017-07-20 um 08 30 12" src="https://user-images.githubusercontent.com/141300/28403616-c7f24d0e-6d25-11e7-85fc-24398c5831eb.png">


as you're probably aware this is how it looks in the Ember CLI API docs and I'd like to change the Ember docs to use a roughly similar layout at some point

**Comment by toddjordan** [comment]
For now just making it italics should do

**Comment by sivakumar-kailasam** [comment]
Closing this since we've made it italics.

<img width="432" alt="screenshot 2018-01-03 11 02 46" src="https://user-images.githubusercontent.com/604117/34509926-a69b758a-f075-11e7-9ad8-5b9314ef1367.png">
