### ISSUE TITLE
add a node test to ensure fastboot works in production mode

### ISSUE THREAD

**Issue by sivakumar-kailasam** [ember-learn/ember-api-docs#297]
we've had a bad case of fastboot failing on heroku which goes unnoticed until reported. Would be nice to have a test that starts our [server module](https://github.com/ember-learn/ember-api-docs/blob/master/bin/ember-fastboot) & checks it for any error in response codes as a part of builds.

**Comment by toddjordan** [comment]
since its not acted on in a few years and has not been pressing issue, closing
