### ISSUE TITLE
Anchor scroll behaviour not working in Firefox and IE

### ISSUE THREAD

**Issue by mhenley-uk** [ember-learn/ember-api-docs#305]
Whilst accessing the Ember API docs via Firefox I'm expecting the docs to respect the anchor flag element in the URL, however it doesn't work as expected. Chrome seems to be working fine. I've also added IE results for completeness. I'm assuming this is down to the existing [bug on **ember-anchor**](https://github.com/mike-north/ember-anchor/issues/46) but raised here too as its an important piece on functionality.

**URL**
https://www.emberjs.com/api/ember/2.14/namespaces/Ember.computed/methods/readOnly?anchor=readOnly

**Screenshots Per Browser**
[Chrome](https://pasteboard.co/GCIkptv.png)
[Firefox](https://pasteboard.co/GCIk38g.png)
[IE](https://pasteboard.co/GCIkCsM.png)
IE testing was kind of blocked by an [associated issue with IE](https://github.com/ember-learn/ember-api-docs/issues/304)

**Extra Details**
- Chromeversion 59.0.3071.115 
- Firefox version 52.2.1 (64-bit) ESR
- IE 11.0.9600.18449

**Comment by MartinMalinda** [comment]
This is probably my mistake.
The scrollable element is being set here:
https://github.com/ember-learn/ember-api-docs/blob/master/app/components/ember-anchor.js#L17

It is `body` in production, while correct selector should probably be `html, body`.
