### ISSUE TITLE
Legacy redirect may lead to strange result

### ISSUE THREAD

**Issue by MartinMalinda** [ember-learn/ember-api-docs#307]
This URL: https://www.emberjs.com/api/classes/String.html
Leads to:
https://www.emberjs.com/api/ember/2.14.1/classes/String?show=inherited%2Cprotected

Which is probably not a correct route and the correct methods there are only available under the `private` filter.

**Comment by jenweber** [comment]
I also noticed some weird redirect from http://emberjs.com/api/classes/Ember.Router.html#method_map

Which is linked as `map()` in the [guides](https://guides.emberjs.com/v2.15.0/routing/defining-your-routes/). It sends users to https://emberjs.com/api/ember/2.15.0/classes/Ember.Router/methods/map?anchor=map&show=inherited,protected,private,deprecated

Related to https://github.com/ember-learn/ember-api-docs/issues/303

**Comment by jenweber** [comment]
PR https://github.com/ember-learn/ember-api-docs/pull/339

**Comment by toddjordan** [comment]
we route most of these to the landing page now, and are dropping support for routing lagacy properties and methods.
