### ISSUE TITLE
Add a clear link to the API docs Github repo

### ISSUE THREAD

**Issue by acorncom** [ember-learn/ember-api-docs#309]
Right now, folks interested in contributing to the app (or reporting bugs) don't have a clear way to arrive at this repo. We should ease that by adding a link (where, I'm not sure) to make it easier to come help us out :grinning:

**Comment by akashdsouza** [comment]
I believe a link should be provided in [Emberjs website repo's](https://github.com/emberjs/website) README under API Documentation

**Comment by acorncom** [comment]
Adjusted the website repo here: https://github.com/emberjs/website/pull/2998, I think it'd still be good to add a link on the actual api site somewhere else well

**Comment by toddjordan** [comment]
We now have a repo link on the api landing page: 
![image](https://user-images.githubusercontent.com/3609063/55298945-82a28b80-53fe-11e9-9f28-a22306597b39.png)
