### ISSUE TITLE
Ember.inject "defined in" links are incorrect

### ISSUE THREAD

**Issue by knownasilya** [ember-learn/ember-api-docs#314]
https://emberjs.com/api/ember/2.14/namespaces/Ember.inject/methods

The method links show the paths correctly, but link to the parent link with the child's line numbers i.e. `inject.service` links to `https://github.com/emberjs/ember.js/tree/v2.14.1/packages/ember-runtime/lib/inject.js#L5` instead of the displayed `packages/ember-runtime/lib/system/service.js:5`

**Comment by kategengler** [comment]
Also wrong for Ember.computed, for example:

https://emberjs.com/api/ember/2.14/namespaces/Ember.computed/methods/notEmpty?anchor=notEmpty

Links to `https://github.com/emberjs/ember.js/blob/v2.14.1/packages/ember-metal/lib/computed.js#L92` vs displayed `packages/ember-runtime/lib/computed/computed_macros.js:92`

**Comment by kategengler** [comment]
Looks like it will be fixed by #319
