### ISSUE TITLE
Autoscroll to methods section is broken

### ISSUE THREAD

**Issue by sivakumar-kailasam** [ember-learn/ember-api-docs#318]
Github links to the methods are broken
https://emberjs.com/api/ember/2.14/namespaces/Ember.computed/methods

Reported via https://github.com/emberjs/website/issues/2971

**Comment by sivakumar-kailasam** [comment]
//cc @MartinMalinda

**Comment by jaredgalanis** [comment]
It looks like across api-docs there are no anchor values for the method, properties, or events tabs. I can take this on.

**Comment by sivakumar-kailasam** [comment]
@jaredgalanis there's an open PR #321 for this one, so may be one of the other open issues?

**Comment by jaredgalanis** [comment]
Ah, got it. Did not see catch that. Yep, I'll take a look.

**Comment by EndangeredMassa** [comment]
Should this be closed? It appears to have been resolved by: https://github.com/ember-learn/ember-api-docs/pull/321

**Comment by sivakumar-kailasam** [comment]
Looks like we broke this again 😿

**Comment by toddjordan** [comment]
Tried listed scenario and works currently.
