### ISSUE TITLE
Using an API version number is not always loading the right version

### ISSUE THREAD

**Issue by RustyToms** [ember-learn/ember-api-docs#333]
I'm so happy that we can filter the docs by version number now, I don't know when that was added but it is really great thanks!

However, sometimes the wrong version of the docs are loading. For example, when I go to https://emberjs.com/api/ember/2.2/namespaces/Ember I generally see that the 2.12 docs load, even though the url is unchanged. I even got 1.12 to load once. Similarly, https://emberjs.com/api/ember/2.1/namespaces/Ember loads the 2.14 docs for me.

I am using Chrome Version 61.0.3163.59 (Official Build) beta (64-bit) on a Mac

**Comment by akashdsouza** [comment]
This is happening because of this line
> https://github.com/ember-learn/ember-api-docs/blob/master/app/services/meta-store.js#L38
Versions 2.12.2 also matches string 2.2 causing it to be the first element of the array which leads to the wrong version being loaded

**Comment by akashdsouza** [comment]
Includes of `includes`, may be we can use `startsWith` ?

**Comment by MartinMalinda** [comment]
I think earlier we had a data structure of versions. Something like this:
```js
versions: [{
  compactVersion: "2.1"
   fullVersion: "2.1.1"
}, {
  compactVersion: "2.14"
  fullVersion: "2.14.3"
}]
```
I think I used that in my PR back then: https://github.com/ember-learn/ember-api-docs/pull/239/files#diff-d1ace59c7fda942c691a37cd9ad5d941R38. This is more explicit and reliable approach. Unfortunately that PR is old and unmergeable right now.

**Comment by jenweber** [comment]
PR https://github.com/ember-learn/ember-api-docs/pull/348
