### ISSUE TITLE
Anchors/Links within Class description don't scroll

### ISSUE THREAD

**Issue by alexander-alvarez** [ember-learn/ember-api-docs#335]
Because of https://github.com/ember-learn/ember-api-docs/blob/master/app/templates/project-version/classes/class.hbs#L41

Eg. when you click `pushPayload` from https://www.emberjs.com/api/ember-data/2.14/classes/DS.Store
you get this url in your address https://www.emberjs.com/api/ember-data/2.14/classes/DS.Store#method_pushPayload but no scroll occurs.
(if you refresh, it does scroll though)

![image](https://user-images.githubusercontent.com/11779993/29935325-58ab6bae-8e4c-11e7-8416-da422fadf066.png)

Could we hook into the behavior that parses the refresh logic into the proper `?anchor=<>` url and https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onhashchange or similar concept?

**Comment by locks** [comment]
Seems fixed!
