### ISSUE TITLE
Invalid urls don't go to 404

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-api-docs#338]
Following this link (or any other invalid link for that matter)
https://emberjs.com/api/classes/Ember.Handlebars.helpers.html#method_input

... results in a really ugly error page displaying "Internal Server Error" or "“Error 503 first byte timeout” cache-iad2144-IAD 1504823668 138679272"

Things to investigate:
- does this type of error occur when run locally?
- Why doesn't the 404 page show up?

**Comment by toddjordan** [comment]
Fixed by https://github.com/ember-learn/ember-api-docs/pull/490
