### ISSUE TITLE
QC changes to the stack for RFC 176

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-api-docs#350]
- [x] make sure that we don't break the api docs for older versions of Ember.
- [x] make version switching work
- [ ] fix so many tests

I tested it for 2.16, 2.11, 1.8, and 1.0. Layout is fine. Styling is meh.

The dropdown menu nav breaks. Fixed in https://github.com/ember-learn/ember-api-docs/pull/351

If you navigate to a 2.16 module, then try to go to 1.8, you get this:

```Error: Assertion Failed: The URL '/ember/1.8/modules/@ember/component' did not match any routes in your application```

Going from 2.11 class to 2.18 causes
```
TypeError: Cannot read property 'split' of undefined
```

**Comment by jenweber** [comment]
Tracked it down to `app/routes/project-version.js`. Making a decision to send the user to the root page in cases that they switch between 2.16 and prior. This is a patch/tech debt. Ideally what should happen here is to do a lookup on some json file/object that contains the past class name mapped to whatever we end up doing for the modules url.

The url is case sensitive, so anything else is too fragile.

**Comment by jenweber** [comment]
### Tech Debt
- [ ] Really, instead of going to the home screen for 2.16 version switching, it ought to map to its equivalent class. Need a reference doc in order to do that.
- [ ] Should write another test for version switching

**Comment by sivakumar-kailasam** [comment]
@jenweber looks like most things in this issue are resolved now. Can we close this?

**Comment by jenweber** [comment]
Yep, remaining issues are captured elsewhere
