### ISSUE TITLE
Older 1.x docs are linking to examples on jsbin that no longer function.

### ISSUE THREAD

**Issue by kitsunde** [ember-learn/ember-api-docs#352]
On: https://guides.emberjs.com/v1.10.0/routing/query-params/ in the bottom it links to jsbin that rely on http://builds.emberjs.com/ember-latest.js which doesn't exist. For example: 

http://output.jsbin.com/tukoye
http://output.jsbin.com/yanigu

Since the newer docs don't seem to have examples, maybe it would be fine to just remove them from the old ones as well.

**Comment by acorncom** [comment]
Thanks for the feedback! Currently our guides infrastructure makes updating old pages a real pain. We've got an initial spike on that here (https://github.com/emberjs/guides/pull/1821) but until that's landed, we pretty much don't update old guides versions 😢  That help?

**Comment by locks** [comment]
Moved issue to guides repository!
