### ISSUE TITLE
Provide some generalized instruction for using the packages syntax

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-api-docs#354]
We need a little blurb that helps people figure out how to use modules/packages instead of Ember.Class in their JS files. Ember.Class will still work.

Related: 
[RFC 176](https://github.com/emberjs/rfcs/blob/master/text/0176-javascript-module-api.md) 
[WIP Blog post](https://github.com/emberjs/website/pull/2984)
[Statusboard modules API explanation](https://emberjs.com/statusboard)

**Comment by jaredgalanis** [comment]
Will get this written up in the morning.

**Comment by jaredgalanis** [comment]
The entire Ember framework was previously imported as a single package. Rather than importing specific parts of the framework directly, a common pattern in Ember was to import the Ember global object and subclass as needed like this:

```
import Ember from 'ember';
export default Ember.Component.extend({
  // ...
});
```

With the introduction of Modules API specific Ember modules may now be imported directly. This allows the building of smaller packages based on the chunk of functionality they provide and importing only parts of the Ember framework that are needed. For example modules will now often look like this:

```
import Component from '@ember/component';
export default Component.extend({
  // ...
});
```

**Comment by jaredgalanis** [comment]
Not sure if the intent was to have code snippets there or not.

**Comment by jaredgalanis** [comment]
@jenweber thoughts? Aside from being unsure about using snippets, also unsure if this is the right area to link out in the same way as the status board update does. I think it's helpful, but not sure if it fits the style of the API docs or not.

**Comment by jenweber** [comment]
I'd swap the order of presentation. Tell people what they *should* do first, then show the old code for comparison purposes. 

I'd also note that the package import names can be found throughout the docs, along with sample code.

**Comment by rtablada** [comment]
I would be careful of calling them packages since they are still only installed with `ember-source` (except for `@ember/string`).

I will check this out some this weekend and read into it, but first 💤 s

**Comment by locks** [comment]
Important things to say:

- Terminology?
- Mental model
  - Chunking
  - classes = default export
  - functions = named export
- Migration
  - `npx ember-modules-codemod`, _or_ the blog post/migration guide
  - ember-rfc-176-data

**Comment by jaredgalanis** [comment]
Beginning in Ember 2.16 Ember will make use of a new JavaScript Modules API. The API was designed to make the structure of the framework more clear and to bring Ember in sync with the increased use of JavaScript modules to import specific libraries. 

Making use of the new JavaScript Modules API allows the building of smaller packages based on pieces of functionality and importing only parts of the Ember framework that are needed. This division of the Ember global object into smaller pieces enhances developer understanding by creating a well defined mental model of the framework by making it clear what functionality is being utilized and by breaking the framework down into more digestible chunks.  Framework classes and utilities are grouped by functionality, making it clear what things are related and how they should work together. 

The most up-to-date and complete mappings between the previous API and the new JavaScript Modules API can be found at the [ember-rfc176-data](https://github.com/ember-cli/ember-rfc176-data) repository.  [Codemod tooling](https://github.com/tomdale/ember-modules-codemod) is also available to help migrate existing Ember projects to the new JavaScript Modules API syntax.

**Comment by locks** [comment]
@jaredgalanis 👌

**Comment by toddjordan** [comment]
@jenweber where were you thinking about putting this text?  is this more of a guides thing?

**Comment by toddjordan** [comment]
ok, I see you guys might be trying to incorporate it on the landing page...  seems like there's a lot y'all want to put there.  Look forward to see how it will look/feel.

**Comment by toddjordan** [comment]
Landing page ✨ ❤️ #454
