### ISSUE TITLE
Get api doc app tests working again

### ISSUE THREAD

**Issue by toddjordan** [ember-learn/ember-api-docs#367]
tests broke  with structural changes with 2.16.  Need to get still valid scenarios to passing again.

**Comment by jenweber** [comment]
The cause of most test failures is a redirect in project-version.js:

```
const modules = model.hasMany('modules').ids().sort();
const module = last(modules[0].split("-"));
return this.transitionTo('project-version.modules.module', model.get('project.id'), model.get('compactVersion'), module);
```

**Comment by jenweber** [comment]
table-of-contents-test.js needs `isShowingNamepaces=true`

```
  this.render(hbs`{{table-of-contents showPrivateClasses=true
                                      projectid=projectId
                                      version=emberVersion
                                      classesIDs=classesIDs
                                      isShowingNamespaces=true
                  }}`);
```

**Comment by jenweber** [comment]
@toddjordan is it intended behavior that when navigating between 2.x projects, it always brings you back to the home screen?

**example of 2.x redirect:**
Visit https://emberjs.com/api/ember/2.11/classes/Ember.Component
Choose 2.8 from the dropdown
End up at https://emberjs.com/api/ember/2.8/modules/ember

**1.x docs work:**
Visit https://emberjs.com/api/ember/1.4/classes/Ember.Component
Choose 1.5 from the dropdown
End up at https://emberjs.com/api/ember/1.5/classes/Ember.Component

**Comment by toddjordan** [comment]
@jenweber weber example above should be fixed with some switching fixes I submitted. (#390)
Also added more tests around version switching.
