### ISSUE TITLE
https://emberjs.com/api/ index seems to not be working

### ISSUE THREAD

**Issue by caseywatts** [ember-learn/ember-api-docs#368]
When I navigate to:
https://emberjs.com/api/

I see:
![image](https://user-images.githubusercontent.com/273653/31406837-c74da42a-add0-11e7-9d12-5254cd57c810.png)

It happens even in an incognito window.

I /can/ successfully navigate to a specific page, it seems to be just the index that's having trouble.
As an example, this page works: https://emberjs.com/api/classes/Ember.computed.html

**Comment by toddjordan** [comment]
There was an issue with the website proxy that was aggressively stripping url encodings from the app's urls.

currently resolved:

![image](https://user-images.githubusercontent.com/3609063/31505298-9a72c30e-af42-11e7-84eb-70fd97c8dda3.png)

**Comment by caseywatts** [comment]
Thanks @toddjordan 🎉
