### ISSUE TITLE
Link to the appropriate code on Github for each method

### ISSUE THREAD

**Issue by acorncom** [ember-learn/ember-api-docs#37]
In the current API docs, when viewing a method there is also an option to view the corresponding code on Github (http://emberjs.com/api/classes/Ember.Router.html#method_didTransition).  It would be ideal to be able to offer that with this new app as well ...

**Comment by acorncom** [comment]
All necessary information seems to exist in the data, it's mainly a matter of displaying this info

**Comment by Gaurav0** [comment]
Fixed by #74

**Comment by acorncom** [comment]
Thanks!
