### ISSUE TITLE
import {assign} from '@ember/polyfills' not listed in API docs

### ISSUE THREAD

**Issue by juwara0** [ember-learn/ember-api-docs#370]
### Problem Description
`assign` is not listed under  `'@ember/polyfills'` in the API docs: https://www.emberjs.com/api/ember/2.16/modules/@ember%2Fpolyfills

### What was expected
`assign` would be listed along with `merge` in the `'@ember/polyfills'` section: https://www.emberjs.com/api/ember/2.16/modules/@ember%2Fpolyfills

**Comment by toddjordan** [comment]
Good catch.  the assign function just needs an `@static` yuidoc annotation to show up in assign.js.

Will do this when we merge the yuidoc changes for 2.16 into ember master...

**Comment by acorncom** [comment]
@toddjordan any pointers on ways other people can help send in the fix for this?

**Comment by toddjordan** [comment]
@acorncom been fixed for a while in ember src.  finally deployed today when we deploy 2.16.1 docs data.
