### ISSUE TITLE
Fix version switching when changing classes/modules

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-api-docs#373]
Right now, if you're look at the documentation for a particular class, and you switch versions between pre-2.16 and post-2.16, it jumps to "home." Fixing this requires having a "map" between the old classes and the new packages.

This is tech debt from a hasty patch: https://github.com/ember-learn/ember-api-docs/pull/351

Currently blocked until RFC 176 documentation gets merged into emberjs source

**Comment by toddjordan** [comment]
Tracking this under #355
