### ISSUE TITLE
Make sure `sortedUniqueItems` is being calculated properly

### ISSUE THREAD

**Issue by locks** [ember-learn/ember-api-docs#375]
The logic at https://github.com/ember-learn/ember-api-docs/blob/master/app/components/api-index-filter.js#L41 is a bit suspicious, as `uniq` does not receive additional parameters, and `sortBy` doesn't have quite that signature, either.

From: https://github.com/ember-learn/ember-api-docs/issues/343#issuecomment-337208263

**Comment by Gaurav0** [comment]
May I just simply recommend https://github.com/lodash/lodash/blob/87730eca06d81a8dcc18adbb62eb1a8fcc8e15b3/sortedUniqBy.js

**Comment by jenweber** [comment]
closed with https://github.com/ember-learn/ember-api-docs/pull/408'

Thanks all for your help!
