### ISSUE TITLE
Link https://emberjs.com/api/ember-data/2.16/classes/Ember redirects to 404 error

### ISSUE THREAD

**Issue by bedrosenator** [ember-learn/ember-api-docs#377]
When I click https://emberjs.com/api/ember-data/2.16/classes/Ember on the page 
https://emberjs.com/api/ember-data/2.16/modules/ember-data
it redirects to 404 error

**Comment by toddjordan** [comment]
Yeah, good catch noticed the same thing.  Unsure ember should be there since its part of the ember project and not ember-data

**Comment by jenweber** [comment]
Related issue, RSVP shows up for ember 1.2-1.6

**Comment by runspired** [comment]
Looking at the docs for 2.16 (and today) and this issue no longer appears.
