### ISSUE TITLE
Deployment/infra related issues

### ISSUE THREAD

**Issue by sivakumar-kailasam** [ember-learn/ember-api-docs#378]
- [ ] We've turned off automated generation of json docs since ember 2.16 didn't have our jsdoc changes merged into it, need to re-enable them
- [x] clearing fastly cache when required needs to be a part of heroku deployment steps to avoid knowledge gaps
- [ ] End to end infra setup of api docs app needs to be documented.

From the team:
- [ ] Have a good staging env for our data
- [x] Set up a more accurate staging env for the app.
- [ ] There’s some weirdness with the data revision/fingerprinting.  may have to do with caching, but we have to figure it out.
- [ ] Ability to update docs for an existing release's generated docs (as it happened with 2.16.0)

**Comment by toddjordan** [comment]
seeing odd behavior when you run a jsonapi docs build over the top of an existing deployment.  For example.  if we want to update the 2.16.0 docs (without a patch release), it creates a lot of "dead" files, as well as files with appended/extra fingerprints.  The tool should remove a specific release if already there.

**Comment by toddjordan** [comment]
We should be able to deploy a specific version without redeploying the whole thing (because of the rev files).  I don't think you can do this at the moment but it seems like something we could add support for.

**Comment by toddjordan** [comment]
Things break on deployments that have seemingly nothing to do with the deployments.  (wrong fingerprinted revisions fetched or are unavailable), despite things looking great in staging.

**Comment by toddjordan** [comment]
Need to have a complete staging environment that matched prod, including app, data, caching, and proxy.

**Comment by toddjordan** [comment]
Moved to feature backlog project https://github.com/ember-learn/ember-api-docs/projects/5
