### ISSUE TITLE
Decide whether to show inherited private methods as we do currently

### ISSUE THREAD

**Issue by acorncom** [ember-learn/ember-api-docs#39]
When viewing classes on the current API system, displaying "private" methods will also display all inherited private methods for a given class (using http://emberjs.com/api/classes/Ember.Router.html as an example, `_lazyInjections` shows in the methods list even though it is defined in the `Ember.Object` class).

In our new data setup, that method won't ever be shown as it's not a public or private method in `Ember.Router`.  I believe this is the appropriate way to handle it, but thought it would be worth mention here (and possibly bringing up with the core team), as any changes to the way API docs are handled tends to also lead to raised voices about missing documentation :smile:

**Comment by acorncom** [comment]
@locks Any comments here?

**Comment by locks** [comment]
@acorncom nope :x do your thang

**Comment by toddjordan** [comment]
Actually it works in a similar way at the moment.  If you check the `private` and `inherited` checkboxes, it will show you private inherited methods, like `_lazyInjections` shown below. 

![image](https://cloud.githubusercontent.com/assets/3609063/23933703/a9dd45c6-0916-11e7-86e0-4b788d3fdb95.png)

I think this behavior is fine for the MVP, therefore closing issue.
