### ISSUE TITLE
DS.JSONAPISerializer methods show docs from DS.JSONSerializer

### ISSUE THREAD

**Issue by NickChristensen** [ember-learn/ember-api-docs#399]
The docs for several methods on `DS.JSONAPISerializer` are being pulled* from `JSONSerializer`, including [extractRelationship](https://emberjs.com/api/ember-data/2.16/classes/DS.JSONAPISerializer/methods/extractRelationship?anchor=extractRelationship) and several others. This results in incorrect function signatures, links to source, and maybe more?

*As far as I understand it, the docs are pulled from the comments in the actual code?

**Comment by jenweber** [comment]
Hi Nick, thanks for bringing this up. You're right that the comments are pulled from the code (then transformed a bit). What you are seeing are methods inherited from the base classes. We have some screening in place to fix it but it looks like some things are slipping through.

Another example:
https://emberjs.com/api/ember-data/2.16/classes/DS.RESTSerializer

**Comment by jenweber** [comment]
Cc @todd.jordan

**Comment by jenweber** [comment]
Cc @toddjordan I can take a look, but in case you are already digging around in the docs

**Comment by toddjordan** [comment]
I'm not sure I follow... `extractRelationship` is inherited from JSONSerializer and is shown when the `inherited` checkbox is checked.  When you uncheck the checkbox the method is not shown.  I think this is the desired behavior.  Am I missing something?

@jenweber ?

**Comment by NickChristensen** [comment]
DS.JSONAPISerializer#extractRelationship isn't inheriting from JSONSerializer, it [defines its own](https://github.com/emberjs/data/blob/1dd87cbdb45a8bbc93c35fdbbe02393221a1dc59/addon/serializers/json-api.js#L302-L320). It also has a different method signature, which Is what threw me off.

**Comment by toddjordan** [comment]
ah, thanks for the clarification.  will look at fixing...

**Comment by toddjordan** [comment]
This isn't a problem with the app, but rather that the JSONAPISerializer doesn't have documentation defined for its own implementation of `extractRelationship`. See https://github.com/emberjs/data/blob/v2.16.0/addon/serializers/json-api.js#L15

**Comment by toddjordan** [comment]
Fixed by #5280.  Should show up when the ember data docs get updated for 2.18.
