### ISSUE TITLE
View on Github link for @ember/object/computed broken

### ISSUE THREAD

**Issue by esbanarango** [ember-learn/ember-api-docs#400]
https://emberjs.com/api/ember/2.16/classes/@ember%2Fobject%2Fcomputed The `View on Github` link on `@ember/object/computed` page is broken.

![screen recording 2017-11-14 at 06 21 pm](https://user-images.githubusercontent.com/1156865/32810384-ad36d4b8-c968-11e7-9e98-d8ec30ee6644.gif)

**Comment by toddjordan** [comment]
That link is no longer showing on the current level of code for that link.  Likely fixed upstream. Closing...
