### ISSUE TITLE
Missing Ember.Logger from API docs

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-api-docs#402]
Original issue here https://github.com/emberjs/ember.js/issues/15866

cc @toddjordan

**Comment by toddjordan** [comment]
opened https://github.com/emberjs/ember.js/pull/15869 to fix

its because at some point logger was refactored into `ember-console`, but the path wasn't added to yuidoc.json

Closing this issue because the fix is to ember.js source and tracked by the original issue above.
