### ISSUE TITLE
init is private???

### ISSUE THREAD

**Issue by Gaurav0** [ember-learn/ember-api-docs#404]
The `init` method is widely documented and used. Why is it marked private?

**Comment by Gaurav0** [comment]
https://emberjs.com/api/ember/2.17/classes/Component/methods/init?anchor=init&show=inherited%2Cprivate

**Comment by jenweber** [comment]
@Gaurav0 you're correct, it's not supposed to be private. The private `init` is coming in from a view mixin and it's bleeding into component docs when it shouldn't be. We're looking into it.

Thank you for raising it, this is a big error.

**Comment by toddjordan** [comment]
Fix PR https://github.com/emberjs/ember.js/pull/15926
