### ISSUE TITLE
support release links

### ISSUE THREAD

**Issue by toddjordan** [ember-learn/ember-api-docs#407]
Instead of referring to links with specific versions, we should support a `release` link, which would redirect to the current release.  This previously was supported, but has since regressed.

example: https://emberjs.com/api/ember/release/classes/Application

**Comment by juventinoromero** [comment]
Hello @toddjordan, I'd like to help with this.

**Comment by toddjordan** [comment]
hi @juventinoromero thanks!  I've got an in progress fix.  What needs to happen now is I need to get the tests working and create new tests that test the new url format.  Feel free to add to the pr, or add the new tests in a new pr

#409

**Comment by juventinoromero** [comment]
@toddjordan ok! I'll see what I can do. Thanks!
