### ISSUE TITLE
computed.readOnly listed twice

### ISSUE THREAD

**Issue by harrisjose** [ember-learn/ember-api-docs#410]
`computed.readOnly` is listed twice in the docs for `@ember/object` ([link](https://www.emberjs.com/api/ember/2.17/modules/@ember%2Fobject))

![Screenshot](https://user-images.githubusercontent.com/10582112/34212483-6b9727e4-e5c2-11e7-8907-7279612ad85a.png).

**Comment by toddjordan** [comment]
Hi @harrisjose thanks for reporting.  Looking into to it.

**Comment by toddjordan** [comment]
This has been fixed by https://github.com/emberjs/ember.js/pull/15958/files but hasn't yet made it into release.  Will make sure this makes it out with the next ember release.
