### ISSUE TITLE
CoreView extends link is broken

### ISSUE THREAD

**Issue by knownasilya** [ember-learn/ember-api-docs#411]
"Extends" link here https://emberjs.com/api/ember/2.17/classes/Ember.CoreView is broken.

**Comment by toddjordan** [comment]
It should be `EmberObject` now instead of Ember.Object in https://github.com/emberjs/ember.js/blob/v2.17.0/packages/ember-views/lib/views/core_view.js#L10

Also, `Ember.Evented` in extends should be just `Evented`

**Comment by toddjordan** [comment]
Looks already to have been fixed in release and beta: https://github.com/emberjs/ember.js/blob/release/packages/ember-views/lib/views/core_view.js

looks like we just need another release and this should be able to be closed.

**Comment by toddjordan** [comment]
Works now in 2.18 https://emberjs.com/api/ember/2.18/classes/Ember.CoreView
