### ISSUE TITLE
Version dropdown menu doesn't allow switching between 2.16-2.17-2.18

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-api-docs#417]
Problem: Can't switch between versions 2.16 and later. Switching between earlier versions still works. 

To do:
- [x] figure out why it is broken and report back
- [x] fix it
- [x] add 2.16, 2.17, and 2.18 to [existing version switching tests](https://github.com/ember-learn/ember-api-docs/blob/master/tests/acceptance/switch-versions-test.js)
- [ ] stretch goal: make tests read version numbers from data rather than hard coding the versions

Tips: Have a read through past patches if you get stuck
https://github.com/ember-learn/ember-api-docs/issues/373
https://github.com/ember-learn/ember-api-docs/issues/333
https://github.com/ember-learn/ember-api-docs/issues/190
https://github.com/ember-learn/ember-api-docs/issues/179
 
![screen shot 2018-01-07 at 1 32 16 pm](https://user-images.githubusercontent.com/16627268/34652650-40e97812-f3af-11e7-8cb2-fa057e71d77d.png)

**Comment by toddjordan** [comment]
Yeah, this isn't good.  Will look at it this week.

**Comment by toddjordan** [comment]
fixed by #418
