### ISSUE TITLE
Inline import examples are wrong for module sub-classes

### ISSUE THREAD

**Issue by toddjordan** [ember-learn/ember-api-docs#420]
For example, I believe 
`import ApplicationInstance from '@ember/application';` should rather be `import ApplicationInstance from '@ember/application/instance';`

and 

`import ComputedProperty from '@ember/object';` should rather be `import ComputedProperty from '@ember/object/computed-property';`

This is happening everywhere there's sub-classes under a module.  Should be a straightforward fix.

**Comment by locks** [comment]
Fixed by linked PR!
