### ISSUE TITLE
Landing Page for API Docs

### ISSUE THREAD

**Issue by toddjordan** [ember-learn/ember-api-docs#429]
going to emberjs.com/api atm goes to the first module in the latest release.  We'd rather have it go to an intro page that gives an overview of using the API docs.

Content/design tbd

**Comment by toddjordan** [comment]
cc: @jenweber @MelSumner

**Comment by jenweber** [comment]
WIP by at least @jenweber and @jaredgalanis

https://github.com/ember-learn/ember-api-docs/tree/feature/landing-page

**Comment by jenweber** [comment]
Content:

## Intro
To get started exploring Ember, choose a version from the dropdown menu and a project (Ember or Ember Data). Ember has core methods used in any app, while Ember Data has documentation of the built-in library for making requests to a back end. If you're looking for documentation of the command line tool used to generate files, build your app, and more, visit [ember-cli docs](https://ember-cli.com/).

## Commonly searched-for documentation

- [Template helpers] - desc
- [computed] - desc
- [Component] - desc
- [Service] - desc
- [get, set, create, and destroy] from `@ember/object` - desc
- [filter, forEach, etc Array methods](http://localhost:4200/ember/2.18.0/classes/Ember.NativeArray)
- [Route]
- [Router]
- [Controller]

**Comment by toddjordan** [comment]
landing page for ember delivered, thanks to  @jenweber and @jaredgalanis
