### ISSUE TITLE
How do I import an npm module whatever

### ISSUE THREAD

**Issue by villander** [ember-learn/ember-api-docs#438]
how do I import an npm module whatever (AMD, commonJS, UMD) in ember-cli?

We should better document this, and ensure the community's ergonomics by putting a third-party library in your app, and adding that into an addon (which is even more painful)

**Comment by toddjordan** [comment]
This is probably more of a guides issue than an api doc

**Comment by villander** [comment]
I think it should be in both places.

**Comment by villander** [comment]
@locks @toddjordan  we need help from the core team or someone who has this knowledge of how to do this for any javascript module for both ember app and ember addons.

**Comment by toddjordan** [comment]
For this stuff we are more talking about ember-cli apis, which are not in this app (yet)

**Comment by sivakumar-kailasam** [comment]
Closing this in favor of https://github.com/emberjs/guides/issues/2017
