### ISSUE TITLE
inline example slightly off with new copy button

### ISSUE THREAD

**Issue by toddjordan** [ember-learn/ember-api-docs#447]
The black strip doesn't extend as far as the other code examples.

Happens at most non-mobile resolutions.  I've only looked on Chrome so far.

![image](https://user-images.githubusercontent.com/3609063/36156412-f3e5c45e-10a4-11e8-874b-fd8df187db8a.png)

**Comment by sivakumar-kailasam** [comment]
<img width="815" alt="screenshot 2018-02-14 18 33 03" src="https://user-images.githubusercontent.com/604117/36205668-8584dd58-11b5-11e8-8f58-9a39d1253bb4.png">
LGTM, can we have someone else confirm?

**Comment by toddjordan** [comment]
did you try hard refreshing, sometimes it looks good but turns out I'm looking at a cached page.

**Comment by toddjordan** [comment]
hint: oddly not happening on my laptop alone, only when plugged into my external monitor.

**Comment by sivakumar-kailasam** [comment]
I'll leave this open for another week before i take it up in case someone at the contributors workshop wants to take this up.
