### ISSUE TITLE
erroneous data on packages left nav on 3.0

### ISSUE THREAD

**Issue by toddjordan** [ember-learn/ember-api-docs#449]
some of these things are not like the others

![image](https://user-images.githubusercontent.com/3609063/36218295-df417826-1181-11e8-9826-668cf5106662.png)

looks like there is some ember documentation issue causing this.  I'm going to patch in api docs app until we fix ember.

**Comment by toddjordan** [comment]
quickly patched by @sivakumar-kailasam .  Leaving opened until we fix in ember

**Comment by sivakumar-kailasam** [comment]
Robert already raised a PR for ember.
