### ISSUE TITLE
Ember Data docs are returning 403

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-api-docs#466]
<img width="1251" alt="screen shot 2018-03-01 at 1 55 21 pm" src="https://user-images.githubusercontent.com/16627268/36863621-394e58ca-1d58-11e8-9354-45721cbde112.png">

**Comment by sivakumar-kailasam** [comment]
I've noticed this a few times in the past few months. This is fixed temporarily but whenever our json-api-generator runs our s3 permissions get messed up again even though it was working before. We'll use this issue to track down and fix this issue properly.

**Comment by toddjordan** [comment]
@sivakumar-kailasam any update on this issue?  Can we close?

**Comment by sivakumar-kailasam** [comment]
We've handled this in the docs generator & it's no longer an issue
