### ISSUE TITLE
transitionToRoute is gone from the API documentation

### ISSUE THREAD

**Issue by cbou** [ember-learn/ember-api-docs#468]
What happens to `transitionToRoute` in the API Documentation?

It was in the 2.18.0 but not in anymore in the 3.0.0.

https://emberjs.com/api/ember/2.18/classes/Controller
https://emberjs.com/api/ember/release/classes/Controller

**Comment by toddjordan** [comment]
Fix needs to made in packages/ember-routing/lib/ext/controller.js in the ember.js repo.

**Comment by toddjordan** [comment]
Fixed in canary

**Comment by toddjordan** [comment]
Will leave open until we can verify in release, so we prevent duplicate issues opened between now and then.

**Comment by toddjordan** [comment]
Fix is in 3.1 and beyond.  Will need a patch release of the docs to fix in 3.0

**Comment by locks** [comment]
The timing for a patch release is long gone 😅
