### ISSUE TITLE
Update Ember to v3.0.0

### ISSUE THREAD

**Issue by Alonski** [ember-learn/ember-api-docs#469]
[comment]: # (Please replace ... with your information. Remove < and >)

### User Story
As a developer I want to be using the latest Ember version while working on the Ember API Docs so that I can use the latest Ember features and not introduce deprecations.

As a user I want a good example of an Ember app with the latest Ember version so that I can learn how to build good Ember apps.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: <Feature>

[comment]: # (Describe the feature you would like, or briefly summarise the bug and what you did, what you expected to happen, and what actually happens. Sections below)
*Summary*: ...
I will update Ember to v3.0.0

#### Expected behavior
[comment]: # (Describe what you expected to happen.)
App will be using Ember v3.0.0

#### Actual behavior
[comment]: # (Describe what actually happened.)
Currently App is using Ember v2.17.0

### Reproduction
[comment]: # (Describe how we can replicate the bug step by step.)
- Run Ember -v
- Look at Ember Version

### Additional Information
Currently there is an issue with the `project.nodeModulesPath` deprecation that is problematic because a few addons that are used by this project throw this deprecation. We can't update to v3.0.0 until these addons are fixed.

**Comment by toddjordan** [comment]
See #470 for PR

**Comment by toddjordan** [comment]
So @Alonski has graciously gotten us most of the way there.  What's left is to test out the current branch that his work is on (3-0-upgrade) and maybe update the rest of the way.  @sivakumar-kailasam  can you remember any issues outstanding that you recall?  Is the project.nodeModulesPath deprecation mention above what is stopping this?

**Comment by toddjordan** [comment]
currently on 3.4 lts
