### ISSUE TITLE
Add Landing Pages for Ember Data and for the app as a whole

### ISSUE THREAD

**Issue by toddjordan** [ember-learn/ember-api-docs#471]
We've delivered a landing page for ember (see #429)

Now we'd also like landing pages for the following URLs:
https://emberjs.com/api/ember-data/release/  - Intro for ember data
https://emberjs.com/api/  - Intro for Ember-family api docs in general

Design and content TBD

**Comment by jenweber** [comment]
@yawboakye 

The ember-data docs landing page can follow similar routing patterns as the main landing page [here in this PR](https://github.com/ember-learn/ember-api-docs/pull/454). 

It should mirror a similar structure as the main landing page [here](https://emberjs.com/api/ember/release), including an intro paragraph and some links to common API. The opening paragraph should be very beginner friendly and help someone understand "what is Ember Data?" You can look at the Guides for inspiration. Any links should use the `release` urls, not specific versions.

I recommend doing a rough first draft, then PR-ing early on to get feedback.

**Comment by toddjordan** [comment]
Moved to feature backlog https://github.com/ember-learn/ember-api-docs/projects/5
