### ISSUE TITLE
'Symbol' is undefined error on IE11 (Windows 7)

### ISSUE THREAD

**Issue by miketeo** [ember-learn/ember-api-docs#477]
Hi, I have encountered the following "whoops" error page when viewing the API pages on IE11.

![error2](https://user-images.githubusercontent.com/6134522/38162107-1bf1e198-350e-11e8-87e4-aa2495564c2e.png)

**Comment by jessica-jordan** [comment]
Just had a look at it and can also reproduce on IE11 of a Win7 - VirtualBox machine:

<img width="1136" alt="screen shot 2018-04-01 at 11 54 12" src="https://user-images.githubusercontent.com/8811742/38171963-c1f06da4-35a3-11e8-87bf-d612e9cfb888.png">


I think enabling the babel polyfill through `ember-cli-babel` as we did on the `builds` page should fix this:
https://github.com/ember-learn/builds/pull/83

**Comment by sivakumar-kailasam** [comment]
@miketeo would you like to try fixing this with a PR :) ?
