### ISSUE TITLE
cannot yarn install with node v9.10.1

### ISSUE THREAD

**Issue by efx** [ember-learn/ember-api-docs#480]
I just cloned this repo, cded into it, and ran the following:
```bash
yarn install v1.5.1
[1/5] 🔍  Validating package.json...
error ember-api-docs@0.1.0: The engine "node" is incompatible with this module. Expected version ">= 8".
error An unexpected error occurred: "Found incompatible module".
info If you think this is a bug, please open a bug report with the information provided in "/Users/eli/floss/efx/ember/ember-api-docs/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I expect to be able to build the project using node 9.10.1.  Could this be whatever validates https://github.com/ember-learn/ember-api-docs/blob/master/package.json#L93 ?

**Comment by toddjordan** [comment]
what version of node do you have?  `node -v`

**Comment by toddjordan** [comment]
oh, nevermind, I see the description (responded from email)

**Comment by efx** [comment]
no worries @toddjordan; I updated the description.

**Comment by toddjordan** [comment]
yeah, thx for reporting.  Could you try removing that engine entry in package.json and see if it works?

**Comment by efx** [comment]
bingo; yarn install starts as I expect when removing that entry.

**Comment by toddjordan** [comment]
ok, will look at this tonight to see if we can find an appropriate fix to represent 8 and above.  Hopefully that gets you going though.  Thanks again for reporting 👍

**Comment by toddjordan** [comment]
Feel free to pr if you find the right way to represent it before then :-)

**Comment by efx** [comment]
I tried the following but it did not work:
```json
  "engines": {
    "node": ">= 8.* || >= 9.*",
    "npm": "5"
  },
```
I had also tried locking down the version numbers, and just including `>=9.*`.
I'm wondering if this is a yarn thing?

**Comment by Gaurav0** [comment]
Workaround: `yarn install --ignore-engines`
