### ISSUE TITLE
Add cross browser testing.

### ISSUE THREAD

**Issue by rwjblue** [ember-learn/ember-api-docs#481]
Look into testing via Browserstack or Sauce Labs in the following browsers:

* IE11
* Safari (last two versions)
* Firefox (last two versions) - This can be done in CI without Browserstack/Sauce Labs.
* Edge (last two versions)
* Chrome (last two versions) - This can be done in CI without Browserstack/Sauce Labs.

There have been a number of reported regressions in emberjs.com on IE11, would be really nice to ensure that we don't accidentally break things in the future...

**Comment by jessica-jordan** [comment]
Looking into the Browserstack setup right now :eyes:

**Comment by sivakumar-kailasam** [comment]
Thanks for setting it up jessica :)
