### ISSUE TITLE
Transitioning from Ember.* class in 2.15 and older docs to 2.16 and newer docs and vice versa is broken.

### ISSUE THREAD

**Issue by Gaurav0** [ember-learn/ember-api-docs#486]
Steps to reproduce (1)

1. Go to https://emberjs.com/api/ember/release/classes/Controller
2. Switch to 2.15 docs

Steps to reproduce (2)

1. Go to https://emberjs.com/api/ember/2.15/classes/Ember.Controller
2. Switch to 2.16 docs

**Comment by toddjordan** [comment]
yeap,  because the class names and hence the urls changed, the route will go to the first package.  We'd have to institute some mapping code for the changes from rfc 176, which is possible with some effort if we wanted this functionality. Not sure I'd call things broken, but indeed not optimal.

**Comment by toddjordan** [comment]
going to close this, and leave it as a limitation for now.
