### ISSUE TITLE
Use the new emberjs.com top banner

### ISSUE THREAD

**Issue by toddjordan** [ember-learn/ember-api-docs#488]
![image](https://user-images.githubusercontent.com/3609063/38623452-b374cb76-3d73-11e8-99f6-51813fac6726.png)

We should reuse where we can.  Check with the guides or deprecation app to see if we can steal 👼

**Comment by axyxnz** [comment]
I can take a look at it.

@toddjordan Is it going to have same menu items as guides or deprecation app?

**Comment by toddjordan** [comment]
Thanks @axyxnz so much for this pr, and sorry its taken us a while to get back around to it.  We're pushing to triage and push our pr/issue backlog down for hacktoberfest so we should be able to look at it in the next couple weeks.
