### ISSUE TITLE
API Left Nav is difficult to use on mobile

### ISSUE THREAD

**Issue by GCheung55** [ember-learn/ember-api-docs#489]
The API left nav isn't mobile friendly. There's a lot of scrolling before getting to the main content and sometimes it's difficult to know when the content has changed.

![api-nav-scroll](https://user-images.githubusercontent.com/46033/38716734-2fa718a6-3e97-11e8-9e64-965ae2484cac.gif)

**Comment by toddjordan** [comment]
wonder if we should put the left nav in something like a hamburger menu for mobile

**Comment by sivakumar-kailasam** [comment]
I guess if we could collapse the nav after a link click on mobile that might be a good start w/o requiring  too many changes

**Comment by toddjordan** [comment]
Moving to feature backlog https://github.com/ember-learn/ember-api-docs/projects/5
