### ISSUE TITLE
Allow deep-linking to package method lists

### ISSUE THREAD

**Issue by kevinansfield** [ember-learn/ember-api-docs#494]
One thing that I've noticed with the recent API docs update is that I've not been able to deep-link to function lists of packages, most notably when linking to Ember's Computed Property Macros list.

I think it would be useful to add IDs to the method list headings and maybe 🔗 icons on hover for easy copying of links.

![screen shot 2018-04-19 at 10 19 10](https://user-images.githubusercontent.com/415/38983660-c30b5254-43bc-11e8-8bc0-005b6eafede6.png)

**Comment by toddjordan** [comment]
Thanks for reporting. I agree we should
