### ISSUE TITLE
ember-data 3.1 paths include the CI build details

### ISSUE THREAD

**Issue by efx** [ember-learn/ember-api-docs#505]
Navigating to https://emberjs.com/api/ember-data/3.1/classes/DS.Model should show the following paths:
<img width="808" alt="screen shot 2018-05-02 at 12 55 50" src="https://user-images.githubusercontent.com/472721/39539400-8238fe92-4e0d-11e8-98bc-3371151c8854.png">
Clicking on it leads to a 404.

**Comment by Dan-Ste** [comment]
I'll take a look at this

**Comment by sivakumar-kailasam** [comment]
@Dan-Ste thanks for reaching out to fix this.  this issue unfortunately requires acres to some parts of our system to fix it. There are a bunch of other issues marked with help wanted label, perhaps you could look into those?

**Comment by Dan-Ste** [comment]
Oh, ok 👍

**Comment by sukima** [comment]
Is this going to get fixed?

**Comment by sivakumar-kailasam** [comment]
@sukima this has been fixed last week.

**Comment by sukima** [comment]
@sivakumar-kailasam Sorry to refute:

![screen shot 2018-08-02 at 10 29 43 am](https://user-images.githubusercontent.com/70075/43590498-1897241c-963f-11e8-9e08-cf2355b11c66.png)

**Comment by sivakumar-kailasam** [comment]
Sorry about that. It should be fixed now. The fix went into ember post 3.3 so any patch releases would resurface this issue & i'll have to manually fix it like i did for 3.3.1. Feel free to reopen it in case you notice this again.
