### ISSUE TITLE
Searching google for "ember computed" gives invalid URL

### ISSUE THREAD

**Issue by rwwagner90** [ember-learn/ember-api-docs#514]
![screen shot 2018-05-16 at 2 36 49 pm](https://user-images.githubusercontent.com/2640861/40201003-a75647ae-59d2-11e8-92c4-2f4b52979634.png)

It is missing the version in the URL. I think before, if you omitted a version, it would default to something, but it does not here.

**Comment by toddjordan** [comment]
Thanks for reporting.  Putting in a fix this evening.
