### ISSUE TITLE
404 when using links or version switcher in left nav

### ISSUE THREAD

**Issue by chbonser** [ember-learn/ember-api-docs#517]
To reproduce:
- visit https://emberjs.com/api/ember/release
- select '3.0' in the version dropdown in the left nav --> 404
- click on any package links in the left nav --> 404

**Comment by sivakumar-kailasam** [comment]
Sorry about that. It's resolved now

**Comment by chbonser** [comment]
@sivakumar-kailasam So fast! Well done!

**Comment by chbonser** [comment]
@sivakumar-kailasam The packages links are fixed but the version dropdown still 404's

**Comment by sivakumar-kailasam** [comment]
@chbonser can you try a hard reload?

**Comment by chbonser** [comment]
hmm... that seemed to do it. Although I could swear I did a shift + reload before bugging you. Thanks again!
