### ISSUE TITLE
Link to the repository in the landing page

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-api-docs#518]
We should have a section at the bottom of the API docs landing page that links to this repo and the ember.js core docs. It should have an explanation of what each does (one sentence).

**Comment by hmbeale** [comment]
I'm going to take a crack at this.

**Comment by toddjordan** [comment]
Hi @hmbeale thanks for looking to contribute!  There's a PR for this already though - #559

**Comment by hmbeale** [comment]
Dang, should have checked.

**Comment by toddjordan** [comment]
fixed!
