### ISSUE TITLE
Clicking a link to a method from ember guides -> ember api docs jumps to wrong place after render

### ISSUE THREAD

**Issue by tchan** [ember-learn/ember-api-docs#519]
Steps to repro:
- Visit https://guides.emberjs.com/v3.1.0/object-model/computed-properties-and-aggregate-data/
- Click ` computed.filterBy` link

Using latest Chrome and attached gif below. When you click the link it loads to the right place for half a second before it fully loads in which it is no longer in the correct spot and you have to scroll down.

![filterby](https://user-images.githubusercontent.com/18437085/40700066-3080482a-641b-11e8-8660-fd66453b16d7.gif)

**Comment by toddjordan** [comment]
This could be a bug in the link in guides which is: https://www.emberjs.com/api/ember/release/classes/@ember%2Fobject%2Fcomputed/methods/alias?anchor=filterBy , which should be https://www.emberjs.com/api/ember/release/classes/@ember%2Fobject%2Fcomputed/methods/filterBy?anchor=filterBy

A fix should be made to ember-learn/guides-source

**Comment by locks** [comment]
Seems fixed.
