### ISSUE TITLE
Google search results for Ember.Logger.error includes broken Api Docs Links

### ISSUE THREAD

**Issue by jpirok** [ember-learn/ember-api-docs#520]
Search google for: Ember.Logger.error.

https://www.emberjs.com/api/ember/release/classes/Ember.Logger/methods

Visiting the link above returns the message below.

ACK! 404 FRIEND, YOU'RE IN THE WRONG PLACE
This page wasn't found. Please try the API docs page. If you expected something else to be here, please file a ticket.

**Comment by toddjordan** [comment]
Searched it just now and the top 3 are as follows
![image](https://user-images.githubusercontent.com/3609063/46232907-d2fd3b80-c33e-11e8-9d73-c5de75297b21.png)

Number one is a non-affiliated to ember chinese site, which is not good.  Number's 2 and 3 are good as the point to the 3.1 version of the documentation before its gone (valid links)

@mansona any ideas on how to knock off the chinese site from the first result?

**Comment by locks** [comment]
This seems addressed.
