### ISSUE TITLE
404 Error for RSVP.hash link on "Specifying a Route's Model" guide

### ISSUE THREAD

**Issue by miketeo** [ember-learn/ember-api-docs#522]
On the guide page at https://guides.emberjs.com/release/routing/specifying-a-routes-model/
the RSVP.hash link under the Multiple Models section redirects to a 404 error page.

The RSVP module is missing from the latest API document.

**Comment by miketeo** [comment]
Seems to be related #487

**Comment by sivakumar-kailasam** [comment]
Closing in favor of #487
