### ISSUE TITLE
Make an Ember Times/blog banner as an experiment

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-api-docs#524]
In light of recent Roadmap posts, we think that increased subscriptions to the Ember times will help address communication issues.

The one page that all Ember devs should be looking at is the API docs (unless they are using Dash). We think a banner might be a good experiment.

We'll launch the banner, and measure if there's an increase in hits/subscriptions across 2 weeks. If there's not, we take it down.

@jessica-jordan is working on this - if anyone else wants to help out, get in touch before doing any work. We still have some brainstorming to do.

**Comment by toddjordan** [comment]
@jessica-jordan is this still something we are planning on doing?  Looking to reduce our issue backlog.

**Comment by toddjordan** [comment]
added to feature backlog https://github.com/ember-learn/ember-api-docs/projects/5
