### ISSUE TITLE
assert is no longer documented

### ISSUE THREAD

**Issue by Gaurav0** [ember-learn/ember-api-docs#529]
The `assert` function is missing from https://emberjs.com/api/ember/release/modules/@ember%2Fdebug

**Comment by Gaurav0** [comment]
Could it be due to this `if (DEBUG)` ?

https://github.com/emberjs/ember.js/blob/v3.2.0/packages/ember-debug/index.js#L87

**Comment by toddjordan** [comment]
its back: https://emberjs.com/api/ember/3.3/functions/@ember%2Fdebug/assert

issue had to do with some refactoring in ember source that hid many documented items
