### ISSUE TITLE
Broken link in ember-data/release/modules/ember-data

### ISSUE THREAD

**Issue by fredericsoumare** [ember-learn/ember-api-docs#531]
![image](https://user-images.githubusercontent.com/37076897/41787666-6d030e5a-7649-11e8-988b-f615566f7ab2.png)

http://localhost:5200/ember-data/release/classes/Ember

**Comment by toddjordan** [comment]
That class shouldn't be there. the fix would be to remove it.  Ember is not part of ember-data

**Comment by toddjordan** [comment]
Thank you so much for reporting 🙇.  #552 is a duplicate of this, and I put a bunch of text around discussing how to fix there, so I'm going to close this issue in favor of that one.
