### ISSUE TITLE
@ember/instrumentation is no longer documented

### ISSUE THREAD

**Issue by ultimatemonty** [ember-learn/ember-api-docs#535]
`@ember/instrumentation` is visible in 2.15 docs. It has not been visible since the new modules API was introduced in 2.16

Package:
https://github.com/emberjs/ember.js/blob/master/packages/%40ember/instrumentation/index.ts

2.15:
![image](https://user-images.githubusercontent.com/7738688/42379099-b2738d6c-80f7-11e8-9db0-e02078d602a4.png)

It is marked as a private API so unsure if it actually *should* be visible. I know it's used by a few addons for perf measurement ([ember-perf](https://github.com/mike-north/ember-perf/blob/master/addon/instance-initializers/ember-perf.js#L1), [ember-perf-timeline](https://github.com/ember-best-practices/ember-perf-timeline/blob/master/addon/initializers/ember-perf-timeline.js#L76)).

Let me know if you need any additional information!

**Comment by sivakumar-kailasam** [comment]
We made a change in the app early this year to hide private packages by default. If you enable the checkbox 'Show Private / Deprecated' you'll see it listed on the packages view.

The direct url hides a few details since the checkbox isn't enabled. That's a problem we'll probably have to look into.

**Comment by toddjordan** [comment]
They are private but you can find them here: https://emberjs.com/api/ember/3.3/modules/@ember%2Finstrumentation

**Comment by toddjordan** [comment]
If you are wanting to bring up the merits of its visibility (private vs public), then the ember.js repo would be a better spot (maybe start on the `#dev-ember` slack channel, or `#topic-performance`)

**Comment by ultimatemonty** [comment]
@toddjordan I think the big thing I was hoping to find in those docs is a list of events that can be subscribed to. The code examples show `render` and `render.handlebars` but it seems like there would be more? I could also be misunderstanding the purpose of the module.
