### ISSUE TITLE
Tutorial link for rsvp si broken

### ISSUE THREAD

**Issue by alexandru-calinoiu** [ember-learn/ember-api-docs#536]
On this page `https://guides.emberjs.com/release/tutorial/autocomplete-component/` when clicking on `Ember's RSVP library.` you will be navigated to a 404 page, I guess the link should point to `https://guides.emberjs.com/v3.1.0/contributing/repositories/#toc_rsvp`

**Comment by sivakumar-kailasam** [comment]
related to #537
