### ISSUE TITLE
There is no information about Ember methods and properties

### ISSUE THREAD

**Issue by allinne** [ember-learn/ember-api-docs#538]
404
https://www.emberjs.com/api/ember-data/release/classes/Ember

**Comment by ko2in** [comment]
These links are also showing 404.
- https://emberjs.com/api/ember/release/classes/Application
- https://emberjs.com/api/ember/release/classes/ApplicationInstance

I think these documentation pages might have published on https://guides.emberjs.com. But, trying to look up these pages  via the following URLs show blank page and catch some JS errors in my browser's console.

- https://guides.emberjs.com/api/ember/release/classes/Application
- https://guides.emberjs.com/api/ember/release/classes/ApplicationInstance
- https://guides.emberjs.com/api/ember-data/release/classes/Ember

**Comment by sivakumar-kailasam** [comment]
@ko2in can you link to the original guides page where you found these links?

@allinne where did you find that URL? it doesn't seem right.

**Comment by toddjordan** [comment]
Thx for reporting. The issue was known. Some code refactoring in the ember
source cut off some of the documentation. Fixed in 3.3.1. New docs to be
deployed shortly

**Comment by ko2in** [comment]
@toddjordan I got these links from the following pages.

- https://guides.emberjs.com/release/applications/applications-and-instances/
- https://guides.emberjs.com/release/applications/dependency-injection/

I'm not sure about the link of Ember class as reported by @allinne.

**Comment by allinne** [comment]
@toddjordan sorry for a delay, I'm on vacation.
I found broken link from this page 
https://emberjs.com/api/ember-data/release/modules/ember-data

**Comment by toddjordan** [comment]
The Application/ApplicationInstance links are fixed on the given pages.  Will need to remove the `Ember` link

**Comment by toddjordan** [comment]
Tracking the Ember link in #552 
Closing this issue since the application links are fixed.
