### ISSUE TITLE
API docs site crashing at boot

### ISSUE THREAD

**Issue by ef4** [ember-learn/ember-api-docs#539]
The API docs app is crashing at boot when you enter via `/` or `/ember/release`. It's not super obvious because the fastboot content is present. But many features include search are broken.

I traced the problem to a discrepancy in the list of available Ember versions. The fastboot shoebox includes `3.3`, and that is presumably why the app is trying to boot with that as the current version. But the data returned from https://ember-api-docs.global.ssl.fastly.net/rev-index/ember.json is missing `3.3` in `meta.availableVersions`. When the current version is missing from that list is causes a crash in the version-lt helper.

**Comment by sivakumar-kailasam** [comment]
Thanks for reporting @ef4. We did a manual deploy and missed flushing the cache. Should be fixed now.
