### ISSUE TITLE
Inheritance information is not properly generated in the docs generator

### ISSUE THREAD

**Issue by acorncom** [ember-learn/ember-api-docs#54]
You can see this problem when viewing the Ember.Component class (https://ember-api-docs.herokuapp.com/ember/2.6.0/classes/Ember.Component)

Currently mixins and parents aren’t currently being handled by Stanley’s setup here: https://github.com/ember-learn/ember-jsonapi-docs  The working setup that currently generates what we're after is here (https://github.com/emberjs/website/blob/master/lib/api_docs.rb), so we'll need to work through things and port the logic over to our node setup.

**Comment by Gaurav0** [comment]
FixedI've added this to my PR at ember-learn/ember-jsonapi-docs#2
