### ISSUE TITLE
Lots of missing modules on API docs for 3.3/release

### ISSUE THREAD

**Issue by patocallaghan** [ember-learn/ember-api-docs#540]
It appears lots of modules are missing from the API docs for the latest release. This results in you getting 404s when you following links from Google.

3.3/Release
https://emberjs.com/api/ember/release/modules/@ember%2Fapplication (404s)
![image](https://user-images.githubusercontent.com/685034/43000547-c69b63c8-8c19-11e8-81cd-1facd3e7ab29.png)

3.2
https://emberjs.com/api/ember/3.2/modules/@ember%2Fapplication
![image](https://user-images.githubusercontent.com/685034/43000533-b9203a0c-8c19-11e8-9fd5-7c457ff95ccf.png)

**Comment by sivakumar-kailasam** [comment]
Thanks for reporting @patocallaghan. Some of these got lost with some internal package refactors. We've made a patch release of ember-source with the missing docs & updated api docs as well.
