### ISSUE TITLE
`getOwner/setOwner` documentation disappeared for 3.3

### ISSUE THREAD

**Issue by nickschot** [ember-learn/ember-api-docs#541]
Docs for 3.2 are here: https://www.emberjs.com/api/ember/3.2/functions/@ember%2Fapplication/getOwner

The 3.3 link results in an error: https://www.emberjs.com/api/ember/3.3/functions/@ember%2Fapplication/getOwner

It seems the same is true for `setOwner`

**Comment by toddjordan** [comment]
find the code in ember.js and make sure: 

* documentation is still there and valid yuidoc
* that the file has an `@module @ember/application` and each function as a `@for @ember/application`
* its in a directory that yuidoc parses (according to yuidoc.json in the root of the ember.js project)

**Comment by ef4** [comment]
This is a reoccurring class of bug. We need automated test coverage in Ember that would require people to explicitly confirm they intended to drop an entry from the API docs.

**Comment by ef4** [comment]
I bisected ember, the offending commit was https://github.com/ember-learn/ember-api-docs/issues/541

**Comment by toddjordan** [comment]
Looks like @Gaurav0 made a fix that has been merged into emberjs.  We need to port that fix to 3.3 and 3.4 and rerun our docs process.

**Comment by Gaurav0** [comment]
The commit was included. :confounded:

**Comment by Gaurav0** [comment]
OK. It looks like `ember-owner` directory was moved to `@ember/-internals` in master at the time I made the commit, but is still in `packages` in Ember 3.5 so just cherry-picking it to 3.5 did not work. :man_shrugging:

**Comment by sivakumar-kailasam** [comment]
Looks like its sorted out now https://api.emberjs.com/ember/3.11/functions/@ember%2Fapplication/getOwner
