### ISSUE TITLE
Ember Data link leads to 404

### ISSUE THREAD

**Issue by pushups** [ember-learn/ember-api-docs#542]
<img width="340" alt="image" src="https://user-images.githubusercontent.com/573678/43603756-c1fea7b0-9648-11e8-8b68-62c54442eca9.png">

1. Go to https://emberjs.com/api/ember/release
2. Click the Ember Data link in the left nav

Result:
User is redirected to a 404 page

Expected result:
The documentation for Ember Data appears.

This only occurs on prod.

**Comment by sivakumar-kailasam** [comment]
Sorry about that. It's sorted out now. Thanks for reporting
