### ISSUE TITLE
Add in the Algolia search box 

### ISSUE THREAD

**Issue by acorncom** [ember-learn/ember-api-docs#55]
It doesn't currently show up in the header but should

**Comment by acorncom** [comment]
Please see https://github.com/ember-learn/guias/issues/15 for additional thoughts on how we might implement this

**Comment by toddjordan** [comment]
@mschinis is currently looking at this.

**Comment by mschinis** [comment]
Sorry for the delay. Started working on this today.

**Comment by toddjordan** [comment]
@sivakumar-kailasam @mschinis This still doesn't appear in production?

**Comment by toddjordan** [comment]
Leaving this open until we get it to show up.

**Comment by sivakumar-kailasam** [comment]
We noticed minor issues when we added it the last time:
- The API docs wasn't indexed
- The group label was missing

**Comment by toddjordan** [comment]
sounds good.  we'll leave this open to track
