### ISSUE TITLE
Missing breadcrumbs and documentation hierarchy context

### ISSUE THREAD

**Issue by JulianLeviston** [ember-learn/ember-api-docs#553]
Hiya folks!

First up, nice new docs. They're very pretty and really generally much nicer looking.

I reckon they could be a bit better to use in this way, though:
Say I go here: https://www.emberjs.com/api/ember/3.4/functions/@ember%2Fobject%2Fcomputed/mapBy

Now, the trouble is there doesn't appear to be any breadcrumbs indicating location in the hierarchy that this function sits within.

Also, if I look at the menu on the left, it doesn't indicate which piece is selected (I'm assuming this is because it's at level 3 in the hierarchy), so unless I already know that `mapBy` docs are found within @ember/object under the computed section (ie https://www.emberjs.com/api/ember/release/modules/@ember%2Fobject ) then it's really not too easy to find my way back to the other computed methods.

I realise this is intimately tied with the new module system, and I really like that. I feel like making a change to fix this issue would improve the discoverability for new users, but also allow experienced users such as myself a massively better experience in terms of discovering where things are now and also just navigating around.

❤️❤️❤️ Keep up the awesome work. I'm going to try to look at seeing if I can help make this change.
Julian — Long time Ember (since before ember data 1).

**Comment by jenweber** [comment]
Hey Julian, thanks for the kind words! You’re right that these are some UX shortcomings.

@toddjordan if someone worked on these things, would it conflict, complement, or duplicate work with your plans for a collapsible menu? I’m thinking a good PR for this issue might do breadcrumbs first.

**Comment by JulianLeviston** [comment]
I just started to look into this. Downloaded and set it up.

**Comment by toddjordan** [comment]
something simple to look at would be to add a package field to functions.
Take for instance the alias function in `@ember/object/computed`:
![image](https://user-images.githubusercontent.com/3609063/46330355-96e90580-c5e0-11e8-91a4-0d33f8e92634.png)

Just add a module field with a link to the package.  Something like
**Module**: [@ember/object](https://emberjs.com/api/ember/3.4/modules/@ember%2Fobject)/computed

Similar to what appears in class pages.
