### ISSUE TITLE
Links back into the source code repos

### ISSUE THREAD

**Issue by JulianLeviston** [ember-learn/ember-api-docs#554]
Hi there,

First up, one of the amazingly cool things about Ember is our community. It's worth taking a moment to appreciate how really wonderful it is. We encourage each other to help, we collectively benefit each other by building upon the work we all did earlier, and we bolster each other by supporting new people and fostering care and a welcoming spirit. That's **really** nice. :heart:

Our website and open-source community-contributed source code is part of this community. So, in the spirit of the embellishing and encouraging on-ramping in the community even more, I feel like it'd be so very cool **if all of our docs linked back into the source code** and improved suggestions about **how we can contribute** to improve what's already close to the state of the art... to encourage new and old users alike to contribute: to give us all a clear path to how *we* can help improve the community even more, especially by empowering us all to make changes ourselves and support the entire community in whatever ways we can manage.

This isn't urgent by any means, just rather something that might encourage new contributors to onramp more smoothly. ❤️ (I'll try to see if I can take a look at the source to work out how this might be thought about or tackled at some stage soon).

**Comment by MelSumner** [comment]
@JulianLeviston can you ping me on Ember Discord so we can discuss more? I'd like to help you make this idea happen.

**Comment by JulianLeviston** [comment]
For others. Discussed. Mel will likely discuss with ember learning team soon. :)

**Comment by toddjordan** [comment]
@MelSumner would like to discuss with you to find out if there is are actionable tasks recorded somewhere so we can close this issue.

**Comment by sivakumar-kailasam** [comment]
Closing this for now. Please reopen this with more details if we have them.
