### ISSUE TITLE
Scroll tests failing in master

### ISSUE THREAD

**Issue by toddjordan** [ember-learn/ember-api-docs#571]
We recently upgraded to ember 2.18 (on our way to the latest), but the last commit is causing our scroll-checking acceptance tests to fail.

See: https://travis-ci.org/ember-learn/ember-api-docs/builds/446971338?utm_source=github_status&utm_medium=notification

```javascript
not ok 602 Chrome 70.0 - [843 ms] - Acceptance | scroll reset on transition: reset scroll on transitions when transition between >=2.16 and <=2.15
    ---
        actual: >
            382
        expected: >
            0
        stack: >
                at Object._callee2$ (http://localhost:7357/assets/tests.js:1717:22)
                at tryCatch (http://localhost:7357/assets/vendor.js:7241:40)
                at Generator.invoke [as _invoke] (http://localhost:7357/assets/vendor.js:7479:22)
                at Generator.prototype.(anonymous function) [as next] (http://localhost:7357/assets/vendor.js:7293:21)
                at step (http://localhost:7357/assets/tests.js:1564:32)
                at http://localhost:7357/assets/tests.js:1575:15
        message: >
            scroll position is zero after transition to different route
        negative: >
            false
        Log: |
            { type: 'warn',
              text: '{} \'fetching by class or module failed, retrying as namespace\'\n' }
            { type: 'error', text: '{}\n' }
    ...
```

**Comment by jeffhertzler** [comment]
I've been looking into this. Essentially it boils down to the fact that the `willTransition` hook is not getting fired for some reason in this case, only the `didTransition` hook is firing. In a probably unrelated note, we are also trying to visit a class that doesn't exist in 2.16 (that's where the error is coming from). Swapping the visit call to use an existing class still doesn't fix the hook not being fired though.

**Comment by toddjordan** [comment]
Seems to be working now.  Last travis run had 0 failures.
