### ISSUE TITLE
Ember Data search results only show up when in the Ember data section

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-api-docs#579]
Steps to reproduce: 

- Navigate to https://emberjs.com/api/ember/release
- search for `hasmany` (intended result Model.hasMany)
- No results found
- Navigate to https://emberjs.com/api/ember-data/release/modules/ember-data (by clicking `Ember Data` in the left nav)
- search for `hasmany`
- Shows results (including the intended result)

Expected behaviour: 
As there is no visual difference between the search on these two pages I do not see any reason to expect that they would return different results based on what page **inside** the api-docs we are on 🤔 

Potential Fixes: 
- add a visual indicator of what index we are searching
  - potentially with some sort of drop-down to pick a different one to what we're currently viewing
- Make sure that all of the indexes show up on all pages of the site

**Comment by filipecrosk** [comment]
It looks like this issue is not happening anymore, at least the results for this `hasmany` search is working on both pages 
![image](https://user-images.githubusercontent.com/194257/53513076-323fb300-3a79-11e9-9cc7-da146d4e565c.png)

**Comment by toddjordan** [comment]
Thanks @filipecrosk for looking at these.
