### ISSUE TITLE
Ember.Templates.helpers page throws 'getEach' of undefined

### ISSUE THREAD

**Issue by cyk** [ember-learn/ember-api-docs#580]
Navigating to [Ember.Templates.helpers](https://emberjs.com/api/ember/release/classes/Ember.Templates.helpers) throws an `Cannot read property 'getEach' of undefined` error and breaks navigation until page is refreshed.

**To repro**

1. Visit https://www.emberjs.com/api/ember/release/classes/Ember.Templates.helpers
2. Click Ember (under Projects in sidebar)
3. Click on Ember.Templates.helpers (under Commonly searched-for documentation)

<details>

![2018-11-30 at 11 55 03](https://user-images.githubusercontent.com/423755/49321963-020b6700-f4c0-11e8-9b0a-072e883b47f7.gif)

</details><br>

This might just be a data issue specific to Ember.Template.helpers. Would it be sufficient to [wrap a conditional check](https://github.com/cyk/ember-api-docs/commit/9cede771e3818ce2bbb88fe213657184dbaa04ae) for `project.projectVersions` to class.hbs template?

**Comment by filipecrosk** [comment]
Could not reproduce this error, I think it's fixed
![screen recording 2019-02-27 at 10 24 am](https://user-images.githubusercontent.com/194257/53513473-27d1e900-3a7a-11e9-888a-a0d732294675.gif)

**Comment by danwenzel** [comment]
Hi @toddjordan - I'm seeing this error if I visit https://api.emberjs.com/ember/3.4/classes/@ember%2Fobject%2Fcomputed/

**Comment by danwenzel** [comment]
Note that I sometimes have to refresh a few times to get the error to show up.  And I'm not noticing that it breaks anything, I just see the error pop up in the console
