### ISSUE TITLE
Github link for source code 404 on API page for `set`.

### ISSUE THREAD

**Issue by deanmarano** [ember-learn/ember-api-docs#581]
When on https://emberjs.com/api/ember/3.5/functions/@ember%2Fobject/set the link circled below

<img width="1173" alt="screen shot 2018-12-04 at 10 09 03 am" src="https://user-images.githubusercontent.com/707107/49470104-c24dc380-f7ce-11e8-8e99-50651a197839.png">

links to https://github.com/undefined/tree/vundefined/packages/ember-metal/lib/property_set.ts#L28

which 404s.

**Comment by prasannavijayan** [comment]
I will look into this.

**Comment by filipecrosk** [comment]
Not able to reproduce this issue anymore, problem solved I think

**Comment by deanmarano** [comment]
Confirmed! Thanks.
