### ISSUE TITLE
Ember.Template.Helpers is missing since 3.1

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-api-docs#583]
Here it is in 3.1:
https://www.emberjs.com/api/ember/3.1/classes/Ember.Templates.helpers

**Comment by Gaurav0** [comment]
It's there:
https://www.emberjs.com/api/ember/3.5/classes/Ember.Templates.helpers

However, transitioning to it from the front page causes an error.

**Comment by toddjordan** [comment]
It doesn't show up in the left nav, I think is what jen was getting at.
