### ISSUE TITLE
Cannot find api docs on RSVP.hash

### ISSUE THREAD

**Issue by uchihamalolan** [ember-learn/ember-api-docs#587]
I was in the page of "specifying Route's Model" in the ember.js guides. In the subsection, "Multiple Models" there was a link to RSVP.hash (api docs). When I clicked the link, it shows error 404.

**Comment by Gaurav0** [comment]
Referred link is here: https://guides.emberjs.com/release/routing/specifying-a-routes-model/#toc_multiple-models

**Comment by habdelra** [comment]
The RSVP.hash link on this page seems to be working now. the link resolves to https://www.emberjs.com/api/ember/release/classes/rsvp/methods/hash?anchor=hash, which is rendering the `RSVP.hash` docs.

<img width="1063" alt="Screen Shot 2019-03-18 at 10 56 24 AM" src="https://user-images.githubusercontent.com/61075/54552180-bdbbae00-496c-11e9-9365-d98d3c8f43e8.png">

**Comment by kennethlarsen** [comment]
Looks like it works now.
