### ISSUE TITLE
Documentation missing for `(has-block)` and (has-block-params)` helpers

### ISSUE THREAD

**Issue by knownasilya** [ember-learn/ember-api-docs#594]
Seems like these come from GlimmerVM, so not sure how those docs would be added to
https://emberjs.com/api/ember/release/classes/Ember.Templates.helpers

**Comment by locks** [comment]
Could you file this under https://github.com/emberjs/ember.js/ instead? I believe that is where it should be documented, as it is Ember that is exposing them from GlimmerVM.

**Comment by habdelra** [comment]
There is a PR for half of this: https://github.com/emberjs/ember.js/pull/17767

**Comment by habdelra** [comment]
Ok, I also added API documentation for `has-block-params` too in the PR above.

**Comment by toddjordan** [comment]
Addressed by #595
