### ISSUE TITLE
Deploy the API docs on api.emberjs.com

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-api-docs#596]
- [x] Remove the `rootURL` implementation for the API docs so that it doesn't need the `/api/` prefix to all paths
- [x] Deploy the branch with no `rootURL` on Heroku
  - We need to old site to still work while we are still swapping over
- [x] Setup a new fastly service for the api app.
- [x] add DNS entry for api.emberjs.com
- [ ] add redirects from emberjs.com/api to api.emberjs.com

**Comment by sivakumar-kailasam** [comment]
The app's live on https://api.emberjs.com.
