### ISSUE TITLE
Remove potentially unused scroll setup

### ISSUE THREAD

**Issue by acorncom** [ember-learn/ember-api-docs#598]
While thinking about the scrolling system in this app, I noticed that https://github.com/ember-learn/ember-api-docs/blob/master/app/initializers/scroll-parent-shim.js appears to be unused.

It would be quite helpful to have someone double-check me on that and if that is indeed the case, to send in a PR with that removed. Doing so would also help reduce our usage of jQuery in the app, which would help with https://github.com/ember-learn/ember-api-docs/issues/441

**Comment by rahulguptaio** [comment]
I'm going to investigate whether this library can be removed
