### ISSUE TITLE
http://api.emberjs.com redirects to Heroku url instead of https://api.emberjs.com and is bypassing Fastly

### ISSUE THREAD

**Issue by mansona** [ember-learn/ember-api-docs#600]
Howdy folks 👋 

Someone in the Ember community Discord noticed this a few weeks ago and it could be the cause of a lot of our performance issues! Especially if any of the people scraping the API docs are using http urls 🙈 

### Steps to recreate 

- visit http://api.emberjs.com
- get redirected to https://ember-api-docs-subdomain-setup.herokuapp.com/ instead of the expected https://api.emberjs.com

I don't know "who" controls the http -> https redirect for the API docs but wherever it is we should update it to redirect properly 👍

**Comment by sivakumar-kailasam** [comment]
I'll have a look

**Comment by sivakumar-kailasam** [comment]
I've disabled the TLS rule on fastly that did this redirection. I've added a module to the fastboot server that should take care of this issue, but it doesn't seem to work on heroku(it works locally & based on the code it should work there too).

Will dig into again when i get more time. For now both http & https versions of the site work.

**Comment by mansona** [comment]
@sivakumar-kailasam am I right in saying that we can do heroku level redirects? I know it can sometimes be hard to get that stuff to work because the heroku redirects aren't great 😭

**Comment by sivakumar-kailasam** [comment]
IMO, I don’t want to make the setup more complex by adding a nginx server in the mix😅 it should be fairly easy to fix this at the fastboot level.

**Comment by sivakumar-kailasam** [comment]
This is now resolved.
