### ISSUE TITLE
Sticky nav on scrolls covers text 

### ISSUE THREAD

**Issue by anpenava** [ember-learn/ember-api-docs#606]
I guess `.sticky-element--sticky-top` needs `z-index` to be set.
<img width="764" alt="Screen Shot 2019-04-03 at 11 20 36" src="https://user-images.githubusercontent.com/18396201/55472126-396f5900-5603-11e9-86de-ce5e921d171c.png">

**Comment by toddjordan** [comment]
Hi, thanks for reporting. Can you give some info on this, like what browser, OS, url, and any other details you think might play into this?.  I don't see what you are seeing on your screen shot.

**Comment by anpenava** [comment]
It is not happening anymore
