### ISSUE TITLE
Ember Data 3.11 docs are missing

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-api-docs#624]
This is a known issue - fixes are pending. The actual work will likely be done in https://github.com/ember-learn/ember-jsonapi-docs or the ember-data codebase

**Comment by sivakumar-kailasam** [comment]
This is fixed by https://github.com/emberjs/data/pull/6252. We're waiting for a 3.11 patch release with that commit to generate the docs.

**Comment by sivakumar-kailasam** [comment]
ember-data 3.11 docs are published
