### ISSUE TITLE
Ember Data 3.4 (LTS) Ember Data API Docs no longer available

### ISSUE THREAD

**Issue by shez-h** [ember-learn/ember-api-docs#633]
We are no longer able to access the Ember Data API docs for  v3.4 @ https://api.emberjs.com/ember-data, we get the 404 page.

**Comment by sivakumar-kailasam** [comment]
Please access it via
https://api.emberjs.com/ember-data/3.4/modules/ember-data while we resolve
the related issue

Regards,
Siva

**Comment by shez-h** [comment]
thanks, that link works

**Comment by sivakumar-kailasam** [comment]
Closing this since we already have issues documenting this behavior
