### ISSUE TITLE
Create Ember Data landing page

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-api-docs#638]
As of PR #637, we made the Ember API landing page show up on Ember Data too. But really, both Ember and Ember Data deserve their own landing pages!

To do:
- Following the same pattern as #637, create a new page that has a list of commonly-searched-for documentation for Ember Data. Use your instincts about what to include - likely models, serializers, and adapters.
- See the PR #637 for where to make the routing changes so that users see it when they visit `release/ember-data`
- If you only get as far as making a list of commonly searched for links, that's ok! Go ahead and make a PR, and other contributors may help with doing the routing.

Here is the landing page that exists today that covers only Ember.js:

<img width="1248" alt="Screen Shot 2020-10-15 at 11 59 53 PM" src="https://user-images.githubusercontent.com/16627268/96211547-99f28c80-0f42-11eb-85b5-4e5322f7fc50.png">

**Comment by runspired** [comment]
Closed by #746 / #761
