### ISSUE TITLE
When searching for attr, clicking a result returns a 404

### ISSUE THREAD

**Issue by Samsinite** [ember-learn/ember-api-docs#640]
Was unable to find `DS.attr` documentation for ember-data, and clicking on any of its search results also resulted in a 404.

**Comment by sivakumar-kailasam** [comment]
On looking into this, searching for `attr` in the search box & clicking on the first result seems to result in 404. 

Additionally `attr` doesn't show up under https://api.emberjs.com/ember-data/release/modules/@ember-data%2Fmodel

**Comment by kategengler** [comment]
The second result also errors. I don't see anything in the network panel, but I see ```Error while processing route: project-version.functions.function Documentation item not found Error: Documentation item not found``` in the console.

**Comment by kategengler** [comment]
https://api.emberjs.com/ember-data/3.13/functions/@ember-data%2Fmodel/attr exists

**Comment by derekwsgray** [comment]
This bug is still there in the 3.17 docs. For something as frequently used as 'attr' to be missing from the API docs is ...unfortunate.

**Comment by Gaurav0** [comment]
The link in the search bar's target is https://api.emberjs.com/ember/3.13/functions/@ember-data%2Fmodel/attr when it should be https://api.emberjs.com/ember-data/3.13/functions/@ember-data%2Fmodel/attr
