### ISSUE TITLE
When switching databases or when databases are updated, local PouchDb doesn't sync.

### ISSUE THREAD

**Issue by Gaurav0** [ember-learn/ember-api-docs#65]
Workaround: In applications tab of Chrome, clear the IndexedDb.

**Comment by Gaurav0** [comment]
This is still happening.

**Comment by Gaurav0** [comment]
So it looks like this is happening because of a fundamental misunderstanding of CouchDb replication. Basically, we have to use the same database, we cannot simply delete it and replace it. Secondly, when updating a document, we have to supply the _rev of the existing document.

For more information about _rev, see https://pouchdb.com/guides/updating-deleting.html#why-must-we-dance-this-dance

**Comment by acorncom** [comment]
As mentioned in #132, we're aiming to shift away from CouchDB to simplify the deploy aspect of this app.  Will close this issue for now.
