### ISSUE TITLE
Setup CD deploys of the backend

### ISSUE THREAD

**Issue by acorncom** [ember-learn/ember-api-docs#66]
We may need to work through what we're wanting to do here, but it would be nice to replace the api build setup in the emberjs/website repo

**Comment by toddjordan** [comment]
This is a wrapper issue for https://github.com/ember-learn/ember-jsonapi-docs/issues/17
Where we need to deploy our data statically to S3

**Comment by toddjordan** [comment]
Also see https://github.com/emberjs/website/pull/2828

**Comment by sivakumar-kailasam** [comment]
The backend push via travis is now operational. We're tracking publishes via build pipeline with https://github.com/ember-learn/ember-jsonapi-docs/issues/30
