### ISSUE TITLE
API docs are broken for 1.x versions

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-api-docs#662]
We confirmed for multiple browsers/regions during the learning team meeting.

<img width="1319" alt="Screen Shot 2019-11-14 at 10 55 09 AM" src="https://user-images.githubusercontent.com/16627268/68873699-02e7d980-06ce-11ea-8f9c-0c47a31db119.png">

**Comment by sivakumar-kailasam** [comment]
The docs weren’t copied over to s3 properly. Syncing them again fixed it
