### ISSUE TITLE
Setup CD deploys of this app

### ISSUE THREAD

**Issue by acorncom** [ember-learn/ember-api-docs#67]

**Comment by sivakumar-kailasam** [comment]
@toddjordan can you add me as a collaborator to the staging app?

**Comment by sivakumar-kailasam** [comment]
@Gaurav0 if you could replace https://github.com/ember-learn/ember-api-docs/blob/master/.travis.yml#L43 with a new app that you own and update the API key in the travis docs, then we'll have successful deploys on merge to the master and production branches.

`travis encrypt $(heroku auth:token) --add deploy.api_key`

**Comment by sivakumar-kailasam** [comment]
I've added my keys temporarily, which should get replaced with an API key of an official account that has access to both staging & production app. It can be done by running `travis encrypt $(heroku auth:token) --add deploy.api_key` .

The current config can deploy to a staging environment on merges to master and to production on merges to production branch. After deployment it restarts the app and flushes redis.

**Comment by toddjordan** [comment]
@sivakumar-kailasam we now also want to change the deployment of this app to S3, similar to what we do with https://github.com/ember-learn/builds

**Comment by toddjordan** [comment]
@acorncom mentioned that he has the api keys and such, if you don't have them already

**Comment by toddjordan** [comment]
I would hold off of an S3 deploy of the app for now, as doing that would be dooming fastboot as I understand. Which would be fine if there is a good SEO alternative (open to suggestions).  We still need to figure out what the long term hosting of the app will be.

**Comment by toddjordan** [comment]
Current situation is we are going to deploy the app to heroku.  Data to be copied to S3 (worked on as part of ember-jsonapi-doc https://github.com/ember-learn/ember-jsonapi-docs/issues/17 )

**Comment by sivakumar-kailasam** [comment]
The heroku section of the travis file seems to be broken. https://travis-ci.org/ember-learn/ember-api-docs/builds/211546164

**Comment by sivakumar-kailasam** [comment]
This is now operational. Merging to master & production deploy to staging & production heroku instances.
