### ISSUE TITLE
Ember 1.13 docs are not accessible

### ISSUE THREAD

**Issue by Samsinite** [ember-learn/ember-api-docs#697]
Hi,

Working on a client whom let their app get enormously out of date, which is running on 1.13, and well noticed that the 1.13 API documentation is not accessible.

**Comment by Samsinite** [comment]
Looks like https://github.com/ember-learn/ember-api-docs/issues/627 reports the same problem, closing in favor of that one.

**Comment by Gaurav0** [comment]
This is a separate issue.

**Comment by Samsinite** [comment]
@Gaurav0 awesome!

**Comment by Gaurav0** [comment]
Fixed by #698
