### ISSUE TITLE
Add a `projects` section to the page

### ISSUE THREAD

**Issue by fivetanley** [ember-learn/ember-api-docs#7]
On the api docs page now, we have something on the left hand page where you can switch between projects

![current ember api docs showing projects page](https://dl.dropboxusercontent.com/s/xuzk1a6m1hvslca/2016-03-10%20at%206.36%20PM.png)

We could use something like that!

The link markup would look something like

```handlebars
{{#link-to 'project' 'ember'}}Ember{{/link-to}}
{{#link-to 'project' 'ember-data'}}Ember Data{{/link-to}}
```

It would be nice if it also had the block-ish look like the current api documentation has where the header has a different background, and the links are in a different box beneath the header, with a box surrounding all of it with a border. tl;dr make it look like the current implementation on emberjs.com/api

**Comment by Gaurav0** [comment]
This is done.

**Comment by acorncom** [comment]
Thanks!
