### ISSUE TITLE
An option provided by the search dropdown leads to a 404 error

### ISSUE THREAD

**Issue by JPKramer707** [ember-learn/ember-api-docs#702]
[See video](https://youtu.be/vNxl7E4cSD0)

**Comment by Gaurav0** [comment]
The link in the dropdown is

https://api.emberjs.com/ember/3.17/classes/Store/methods/queryRecord?anchor=queryRecord

fails because Store is in ember-data, not ember.

**Comment by Gaurav0** [comment]
Same issue as #640
