### ISSUE TITLE
api.emberjs.com is down - leads to Heroku "nothing here yet" page

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-api-docs#712]
Workaround for users - go directly to https://api.emberjs.com/ember/release

My hunch is this seems to be a problem with redirects since going to a specific path is ok.

**Comment by locks** [comment]
I basically "turned it off and on again" by rolling back to an earlier deploy and then rolling forward to the latest deploy and it worked. I don't have much more insight at the moment 🤔 We should set up an alert in case we run into this situation again.

**Comment by amyrlam** [comment]
It sounds like @sivakumar-kailasam transferred pingdom email alert to @MelSumner (am not familiar with pingdom myself, but sounds like it sets up a job that periodically checks the api docs URL, and if it's not up, sends an email.

Question: Was it a bad deploy after merge / green CI? If so, checking the deploy was successful should be part of merging a PR to the repo?

**Comment by Gaurav0** [comment]
@amyrlam Right now there is no ci deploy; we manually deploy and check it. The site did not go down after a deploy; it went down randomly AFAICT. In fact, master is currently ahead of the production deploy.
