### ISSUE TITLE
peekAll Api doc missing

### ISSUE THREAD

**Issue by jjff** [ember-learn/ember-api-docs#714]
v3.17  https://api.emberjs.com/ember/release  top right seach for "store" and there e.g. for peekAll --> https://api.emberjs.com/404

**Comment by Gaurav0** [comment]
This has been fixed, we need a deploy. @locks

**Comment by sivakumar-kailasam** [comment]
created a review app

**Comment by Gaurav0** [comment]
fixed by #716
