### ISSUE TITLE
"Defined in" links point to a non-existing version

### ISSUE THREAD

**Issue by locks** [ember-learn/ember-api-docs#722]
At the moment `v3.18.1` API docs link to a non-existing 3.18.3 tag on GitHub.

**Comment by Gaurav0** [comment]
@locks It appears that https://api-store.emberjs.com/rev-index/ember.json contains references to a version 3.18.3

**Comment by sivakumar-kailasam** [comment]
Did anyone try rerunning the app locally to see if the issue is reproducible?

**Comment by Gaurav0** [comment]
Yes. Running the app locally refers to the same s3 resources, so shows the same problem. Running the app against ember-jsonapi-docs does not seem to reproduce the issue,

**Comment by sivakumar-kailasam** [comment]
oh i didn't notice the repo, i meant to ask if rerunning ember-jsonapi-docs fixes the issue. Since it does, someone with aws keys should run it again & publish the docs to s3 again.

**Comment by Gaurav0** [comment]
@locks @mansona Can one of you try this?

**Comment by locks** [comment]
I have tried it twice since the initial release and it didn't seem to help, but I'll try again!

**Comment by Gaurav0** [comment]
@locks Thank you. Is there any way I can help?

**Comment by locks** [comment]
I think this has since been addressed!
