### ISSUE TITLE
Replace deprecated EmberApp.concatFiles() calls with broccoli-concat

### ISSUE THREAD

**Issue by toddjordan** [ember-learn/ember-api-docs#73]
getting the following on startup:
![image](https://cloud.githubusercontent.com/assets/3609063/20326792/3e6c657c-ab58-11e6-9b2d-e4a08a78e614.png)

**Comment by Gaurav0** [comment]
These are coming from the old ember-cli-fastboot. If we can update, they will go away.

**Comment by toddjordan** [comment]
cool, I'll close in favor of #68
