### ISSUE TITLE
Update the landing page to link to most common Octane concepts

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-api-docs#731]
The [home page of the API docs](https://api.emberjs.com/ember/release) has a list of commonly-searched-for documentation, but it is missing some things! Add links for:
-The Components bullet point should link to both "Classic Components" (the existing link) and [Glimmer Components](https://api.emberjs.com/ember/release/modules/@glimmer%2Fcomponent)
- [Tracked](https://api.emberjs.com/ember/3.21/functions/@glimmer%2Ftracking/tracked)
- The `{{on}}` and `{{fn}}` helpers

The file you need to change is [here](https://github.com/ember-learn/ember-api-docs/blob/master/app/templates/project-version/index.hbs)

**Comment by JamesS-M** [comment]
I would like to work on this @jenweber

**Comment by ijlee2** [comment]
Thanks, @JamesS-M. I assigned the issue to you but may ask @jenweber to review your pull request.
