### ISSUE TITLE
Remove outdated import paths advice from the landing page

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-api-docs#732]
The "How to import and use packages" section should be removed from the [api docs landing page](https://api.emberjs.com/ember/release). It was aimed at when we rearranged all the package import paths a long time ago.

The file you should change is here: https://github.com/ember-learn/ember-api-docs/blob/master/app/templates/project-version/index.hbs

**Comment by cah-johnryan** [comment]
EmberFest Contributors Workshop: I am going to take a shot at this now
