### ISSUE TITLE
Update a redirect for the ember data legacy modules

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-api-docs#735]
Between Ember Data 3.20 and 3.21, the `@ember-data` module was removed. However, we had some redirects from long ago that try to send people to this page. We should instead redirect them to the ember data index.

To-do:
- in `app/routes/data-class.js`, check if the new URL is to go to `@ember-data`. If it does, instead redirect to the index.
- It is expected that a test should fail after your change. Update the `should convert url for legacy ember data module` test to assert that you are redirected to the index page for ember data, `/ember-data/release`

**Comment by Ian-Yy** [comment]
Hi, may I try to do this?

**Comment by jenweber** [comment]
It would be great to have your help! Thank you! If you get stuck and want to chat about it, you can find people to pair with in Ember’s Discord, in the dev-Ember-learning and Hacktoberfest channels: https://emberjs.com/community

**Comment by Ian-Yy** [comment]
Hi, I've just created a PR. Please let me know if I am wrong and need to change. Thank you.

**Comment by Ian-Yy** [comment]
Hi @ijlee2 @jenweber, may I know if my PR is ok?
