### ISSUE TITLE
API docs appear to be down

### ISSUE THREAD

**Issue by runspired** [ember-learn/ember-api-docs#747]
can't select version the dropdown, almost all links 404ing

**Comment by ijlee2** [comment]
@runspired Hmm. Can you try visiting the API docs again? I think I'm able to visit the site, select a different version of Ember, and click on internally redirected links.

**Comment by runspired** [comment]
@ijlee2 I think it was a deploy issue that maybe has resolved. I had landed on the 3.26 docs. After a lot of refreshing I got to the 3.25 docs and then everything worked. I forget what causes this but we've hit it before.
