### ISSUE TITLE
Bug: Link to @glimmer/tracking/primitives/cache is a 404

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/ember-api-docs#751]
This link is a 404: https://api.emberjs.com/ember/release/modules/@glimmer%2Ftracking%2Fprimitives%2Fcache

![ember-bug](https://user-images.githubusercontent.com/1372946/117075099-1edba280-ace9-11eb-8b03-c1c38a7dbf4a.gif)

Reported: https://discord.com/channels/480462759797063690/480777444203429888/839224958660116533

**Comment by amyrlam** [comment]
Note: "Please file a ticket" on /404 isn't as visible / noticeable as the "edit on GitHub pencil" that we have on the guides. 

Look at that as part of this issue, or potentially break out into a separate issue

**Comment by amyrlam** [comment]
@mansona reports that the new redesign has exactly this functionality (edit on GitHub), just the API docs and the guides are in progress cc @elwayman02 re: https://discord.com/channels/480462759797063690/480777444203429888/839448567630004274

**Comment by amyrlam** [comment]
From running locally: 

![image](https://user-images.githubusercontent.com/1372946/117182877-c01b3500-ad8b-11eb-94c5-ed0ed1e68fdb.png)

**Comment by jenweber** [comment]
We suspect that the problem is that there are 3 segments to the path. The router only supports 2.

**Comment by amyrlam** [comment]
@elwayman02 This is fixed locally, but not on production. There is a separate, larger issue with deploys that this issue helped uncover, that we are tracking https://github.com/ember-learn/ember-api-docs/pull/758 for now. More to come, thanks again for reporting!

**Comment by mansona** [comment]
again a bit trigger happy with the closing of the issue 😂 we've solved the issues we had with deployment and we're going to go live tomorrow (in the morning for me - 10ish hours from now) 

**then** we can close this issue 😂

**Comment by amyrlam** [comment]
Fixed now cc @elwayman02! Huge thank you @mansona!
