### ISSUE TITLE
@ember/component/template-only page is blank

### ISSUE THREAD

**Issue by amyrlam** [ember-learn/ember-api-docs#756]
https://api.emberjs.com/ember/release/modules/@ember%2Fcomponent%2Ftemplate-only is a blank page below the header, no content 

Note: ember.js publishes yuidoc JSON, ember-jsonapi-docs transforms that JSON and puts it in S3, ember-api-docs is the front end display layer

- Run emberjs repo `cd ember.js && npx yuidoc . --server`, see if the docs are actually there at the source in yuicdoc? 
- May relate to https://github.com/ember-learn/ember-api-docs/issues/751

cc @jenweber

**Comment by Windvis** [comment]
Related issue over in the ember.js repo: https://github.com/emberjs/ember.js/issues/19325 which should be fixed by https://github.com/emberjs/ember.js/pull/19553 :smile:.
