### ISSUE TITLE
Documented object properties are not displayed

### ISSUE THREAD

**Issue by sandydoo** [ember-learn/ember-api-docs#765]
One example is the [`deprecate` method](https://api.emberjs.com/ember/3.26/functions/@ember%2Fdebug/deprecate). I often forget what the options are and which of them are required. The current docs don’t show them, but they are [documented in the source](https://github.com/emberjs/ember.js/blob/v3.26.1/packages/%40ember/debug/lib/deprecate.ts#L177). I'm not sure if there are any more examples like this.

### Proposal

I propose we display these props. An indent should be enough to differentiate them from the function arguments.

#### Before

![before](https://user-images.githubusercontent.com/7572407/121737545-ad6deb80-cb01-11eb-821b-97e49eee7e7e.jpg)

#### After

![after](https://user-images.githubusercontent.com/7572407/121737534-ab0b9180-cb01-11eb-8f70-389097c7ff2d.jpg)

**Comment by jenweber** [comment]
Hello! This is now live. Our deployment pipeline had an issue blocking deployments, and it's fixed now. Thanks again for your work on this!
