### ISSUE TITLE
Replace jquery animation

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-api-docs#769]
The table of contents has an animation where, when you click some categories in the table of contents, they collapse or expand.

This is the last use of jquery in this app, so if we can remove it, we will reduce bundle size!

To do:
- Replace the animation with a plain CSS + JavaScript animation (no liquid fire or Ember animated)
- Write a test if there isn’t already one

Thanks for the help!

**Comment by swarajpure** [comment]
I'd like to work on this one. Can I get this assigned to me please?

**Comment by jenweber** [comment]
Done! Thanks for working on this.
