### ISSUE TITLE
Algolia search is broken

### ISSUE THREAD

**Issue by ctjhoa** [ember-learn/ember-api-docs#788]
**Reproduction steps**
- Go to https://api.emberjs.com/ember/release
- Type any existing method in the search bar (eg. `factoryFor`)
- Note that suggested links are weird (eg. `https://api.emberjs.com/ember/release/classes/ember/methods/4.1?anchor=factoryFor`; suppose to be `https://api.emberjs.com/ember/4.1/classes/ApplicationInstance/methods/factoryFor?anchor=factoryFor`)
- Click on any suggested links
- You are redirected to https://api.emberjs.com/404

Browsers: Firefox 94.0.2, Chromium 96.0.4664.45

**Comment by jenweber** [comment]
Thank you so much for reporting this! We are looking into it.

**Comment by jenweber** [comment]
Search should be working in production now. I deployed a much earlier commit (`jw-search-debugging-2`) to get search working and buy us some time to find the bug.

I discovered that this is a front end problem in the ember app itself. It sure has the look of a mistake in some logic, where we are putting the version number where the path to the method should be.  This app went through a ton of revisions recently and it seems we missed something.

**Comment by jenweber** [comment]
@mansona is going to have a look at this.

Examples:

Broken: http://localhost:4200/ember/release/classes/ember/methods/4.1?anchor=forEach
Correct https://api.emberjs.com/ember/4.1/classes/EmberArray/methods/forEach?anchor=forEach

Acceptance test we want to write:

- start at homepage
- does a search
- makes sure it goes to the right place
