### ISSUE TITLE
fix favicon

### ISSUE THREAD

**Issue by toddjordan** [ember-learn/ember-api-docs#79]

**Comment by acorncom** [comment]
Looks like there are two favicons in the app at the moment (https://github.com/ember-learn/ember-api-docs/blob/master/public/assets/images/favicon.png and https://raw.githubusercontent.com/ember-learn/ember-api-docs/master/public/favicon.ico) as well as it being referenced here: https://github.com/ember-learn/ember-api-docs/blob/master/app/index.html#L10

**Comment by Gaurav0** [comment]
Works for me.

**Comment by toddjordan** [comment]
oddly, favicon is in source control, I see it when deployed, but not in dev mode.  I think it has to do with not having {{rootURL}}
