### ISSUE TITLE
main layout scrolls behind top banner, messes with anchoring

### ISSUE THREAD

**Issue by toddjordan** [ember-learn/ember-api-docs#80]
![anchor-issue](https://cloud.githubusercontent.com/assets/3609063/20510771/f7c7194e-b040-11e6-8c68-0df33d4e4ad3.gif)

**Comment by oskarrough** [comment]
I think it could be argued that the site would be better off without a fixed banner. It's not used to navigate the actual API and you win screen real estate :house_with_garden: 

I can open a PR to make it static.

**Comment by acorncom** [comment]
@oskarrough 👍 We don't have a static header on the guides site, so not sure why it's fixed here at the moment ...

**Comment by Gaurav0** [comment]
Change was made by @tehviking (scrolly sidebar)

**Comment by tehviking** [comment]
My recollection is fuzzy but I did this against a deadline to help with stuff at EmberConf, and it got merged like a bunch of months later. Ain't nobody gonna hurt my feelings if that commit needs to be reverted. If I need to look at this it'll be a couple days.

**Comment by acorncom** [comment]
@tehviking Don't think we'll need you specifically to work on it (unless you're dying for things to do 😀). I imagine life is a tad busy with the work transition on your end ...

**Comment by tehviking** [comment]
True. I cannot believe how much work it is to get a job!
