### ISSUE TITLE
Need formatting in details

### ISSUE THREAD

**Issue by toddjordan** [ember-learn/ember-api-docs#82]
Example in current api docs:
![image](https://cloud.githubusercontent.com/assets/3609063/20511374/d6cf387a-b045-11e6-8490-41c3895aa7b2.png)

Example in app:
![image](https://cloud.githubusercontent.com/assets/3609063/20511381/e5b52cdc-b045-11e6-8527-f193b631c159.png)

**Comment by oskarrough** [comment]
Any preferences for the implementation, does something already exist? Or do you want to use a https://github.com/isagalaev/highlight.js/ component?

**Comment by Gaurav0** [comment]
Ideally we would use something that produced the same output as on our existing site.

**Comment by acorncom** [comment]
@Gaurav0 @tehviking This might be useful here: https://github.com/ef4/ember-code-snippet

**Comment by toddjordan** [comment]
Possibly ignorant question: Why is this already working for class details, but not for method/property/event details, and can they be handled in the same place?

**Comment by Gaurav0** [comment]
Class details are in HTML format while field details are in Markdown format for some reason.

**Comment by toddjordan** [comment]
its in markdown in the code:
https://github.com/emberjs/ember.js/blob/master/packages/ember-glimmer/lib/component.js

I think ember-jsonapi-docs is converting it.  Maybe we should also convert class/method/event details there as well.
https://github.com/ember-learn/ember-jsonapi-docs/blob/f7c1ffa868e5242c3414f69d2c089fbbd90893f1/index.js#L56

**Comment by toddjordan** [comment]
I created a PR for rendering the markdown at build time in ember-jsonapi-docs: https://github.com/ember-learn/ember-jsonapi-docs/pull/6

**Comment by toddjordan** [comment]
![image](https://cloud.githubusercontent.com/assets/3609063/20758749/cf1cf62c-b6e8-11e6-98d2-56cb937fdf22.png)
