### ISSUE TITLE
Redesign - style the function arguments and return type section

### ISSUE THREAD

**Issue by jenweber** [ember-learn/ember-api-docs#845]
File to work in: `app/components/class-field-description.hbs`

Style the "name" and "returns" section. Do not worry about the code block.

Currently, it looks like this in the WIP branch:

<img width="695" alt="Screen Shot 2022-12-05 at 12 00 36 PM" src="https://user-images.githubusercontent.com/16627268/205697196-a20e2f78-0469-4d70-90ba-7e8c96f9caaf.png">

How it looks in production:

<img width="480" alt="Screen Shot 2022-12-05 at 12 01 40 PM" src="https://user-images.githubusercontent.com/16627268/205697416-57c5b761-d189-4179-bd6a-9b0b2e38aff2.png">

**Comment by MehulKChaudhari** [comment]
Hey Jen, I would like to work on this issue.
