### ISSUE TITLE
ember-data 3.28 links aren't working

### ISSUE THREAD

**Issue by apellerano-pw** [ember-learn/ember-api-docs#890]
Steps to reproduce:

1. Navigate to ember-data api site
2. Change version selector to 3.28
3. Click a link in the left nav or page content

Expected behavior:

See docs for clicked item

Actual behavior:

404 page

**Comment by jenweber** [comment]
Thank you for reporting. We have just soft launched some new infra that likely introduced this bug. We will take a look!

cc @mansona

**Comment by jenweber** [comment]
Work is underway to fix this. PR for fixing another version: https://github.com/ember-learn/ember-api-docs-data/pull/13
